import { getRandomInt } from "isaacscript-common";

export const FUNNY_ACTION_TEXT_SET: ReadonlySet<string> = new Set([
  "upon uninstalling Isaac,",
  "upon opening discord,",
  "upon selling your organs to the black market,",
  "after winning the game,",
  "instead of being born once,",
  "upon doing literally nothing,",
  "on cooking with mama,",
  "a wise man once said:",
  "upon writing the obituary,",
  "don't",
  "upon standing still for two days,",
  "upon updating to windows 11,",
  "every 3-7 days,",
  "every 3-7 business days,",
  "upon donating to charity,",
  "upon twisting and shouting,",
  "upon twirling your mustache,",
  "upon menstruating,",
  `every 2-${getRandomInt(1, 24)} hours,`,
  "on updating this mod,",
  "instead of leaving a cookie out for santa,",
  "instead of picking up this item,",
  "upon circling a tinted rock 20 times,",
  "upon going back and fourth through a door 33 times,",
  "instead of going to The Chest,",
  "when the moon passes between the sun and the earth,",
  "when you forget to turn off the oven,",
  "after screaming loudly into the mic,",
  "after turning your pc off,",
  "every blink,",
  "every time you think an original thought,",
  "every time you [REDACTED],",
  "every time you comment on this mod's Steam page with '[DELETED]',",
  "every time you receive an anonymous love letter,",
  "every time you erase henry,",
  "every time you use Book of Shadows at game coordinates 23.76, 32.39 while playing as blue baby,",
  "instead of spending all your money on used pokemon cards, eventually going bankrupt and resorting to a life of crime and violence,",
]);
