export const CollectibleTypeCustom = {
  BITFLIP: Isaac.GetItemIdByName("Bitflip"),
  BITFLIP_PINK: Isaac.GetItemIdByName(" Bitflip"),
  BITFLIP_BLUE: Isaac.GetItemIdByName("  Bitflip"),
  D14: Isaac.GetItemIdByName("D-14"),
  TRASH: Isaac.GetItemIdByName("Trash"),
  EXTRACT: Isaac.GetItemIdByName("Extract"),
  EXTRACT_FIRE: Isaac.GetItemIdByName(" Extract"),
  MYDOOM_EYE_STAGE_1: Isaac.GetItemIdByName("Qdwho Uou  "),
  MYDOOM_EYE_STAGE_2: Isaac.GetItemIdByName("Kfiuj Uou  "),
  MYDOOM_EYE_STAGE_3: Isaac.GetItemIdByName("Cyhqsbu Uou  "),
  MYDOOM_EYE_STAGE_4: Isaac.GetItemIdByName("Xkdwho Uou  "),
  ZAZZ: Isaac.GetItemIdByName("Corrupted Passive"),
  ZAZZ_ACTIVE_NORMAL_0: Isaac.GetItemIdByName(" "),
  ZAZZ_ACTIVE_NORMAL_0_COPY: Isaac.GetItemIdByName(" ."),
  ZAZZ_ACTIVE_NORMAL_1: Isaac.GetItemIdByName("  "),
  ZAZZ_ACTIVE_NORMAL_1_COPY: Isaac.GetItemIdByName("  ."),
  ZAZZ_ACTIVE_NORMAL_2: Isaac.GetItemIdByName("   "),
  ZAZZ_ACTIVE_NORMAL_2_COPY: Isaac.GetItemIdByName("   ."),
  ZAZZ_ACTIVE_NORMAL_3: Isaac.GetItemIdByName("    "),
  ZAZZ_ACTIVE_NORMAL_3_COPY: Isaac.GetItemIdByName("    ."),
  ZAZZ_ACTIVE_NORMAL_4: Isaac.GetItemIdByName("     "),
  ZAZZ_ACTIVE_NORMAL_4_COPY: Isaac.GetItemIdByName("     ."),
  ZAZZ_ACTIVE_NORMAL_5: Isaac.GetItemIdByName("      "),
  ZAZZ_ACTIVE_NORMAL_5_COPY: Isaac.GetItemIdByName("      ."),
  ZAZZ_ACTIVE_NORMAL_6: Isaac.GetItemIdByName("       "),
  ZAZZ_ACTIVE_NORMAL_6_COPY: Isaac.GetItemIdByName("       ."),
  ZAZZ_ACTIVE_NORMAL_7: Isaac.GetItemIdByName("        "),
  ZAZZ_ACTIVE_NORMAL_7_COPY: Isaac.GetItemIdByName("        ."),
  ZAZZ_ACTIVE_NORMAL_8: Isaac.GetItemIdByName("         "),
  ZAZZ_ACTIVE_NORMAL_8_COPY: Isaac.GetItemIdByName("         ."),
  ZAZZ_ACTIVE_NORMAL_9: Isaac.GetItemIdByName("          "),
  ZAZZ_ACTIVE_NORMAL_9_COPY: Isaac.GetItemIdByName("          ."),
  ZAZZ_ACTIVE_NORMAL_10: Isaac.GetItemIdByName("           "),
  ZAZZ_ACTIVE_NORMAL_10_COPY: Isaac.GetItemIdByName("           ."),
  ZAZZ_ACTIVE_NORMAL_11: Isaac.GetItemIdByName("            "),
  ZAZZ_ACTIVE_NORMAL_11_COPY: Isaac.GetItemIdByName("            ."),
  ZAZZ_ACTIVE_NORMAL_12: Isaac.GetItemIdByName("             "),
  ZAZZ_ACTIVE_NORMAL_12_COPY: Isaac.GetItemIdByName("             ."),
} as const;
