export const CollectibleTypeCustom = {
  BITFLIP: Isaac.GetItemIdByName("Bitflip"),
  BITFLIP_PINK: Isaac.GetItemIdByName("Bitflip "),
  D14: Isaac.GetItemIdByName("D-14"),
  TRASH: Isaac.GetItemIdByName("Trash"),
  EXTRACT: Isaac.GetItemIdByName("Extract"),
  EXTRACT_FIRE: Isaac.GetItemIdByName(" Extract"),
  ZAZZ: Isaac.GetItemIdByName("Corrupted Passive"),
  ZAZZ_ACTIVE_NORMAL_0: Isaac.GetItemIdByName(" "),
  ZAZZ_ACTIVE_NORMAL_0_COPY: Isaac.GetItemIdByName(" ."),
  ZAZZ_ACTIVE_NORMAL_1: Isaac.GetItemIdByName("  "),
  ZAZZ_ACTIVE_NORMAL_2: Isaac.GetItemIdByName("   "),
  ZAZZ_ACTIVE_NORMAL_3: Isaac.GetItemIdByName("    "),
  ZAZZ_ACTIVE_NORMAL_4: Isaac.GetItemIdByName("     "),
  ZAZZ_ACTIVE_NORMAL_5: Isaac.GetItemIdByName("      "),
  ZAZZ_ACTIVE_NORMAL_6: Isaac.GetItemIdByName("       "),
  ZAZZ_ACTIVE_NORMAL_7: Isaac.GetItemIdByName("        "),
  ZAZZ_ACTIVE_NORMAL_8: Isaac.GetItemIdByName("         "),
  ZAZZ_ACTIVE_NORMAL_9: Isaac.GetItemIdByName("          "),
  ZAZZ_ACTIVE_NORMAL_10: Isaac.GetItemIdByName("           "),
  ZAZZ_ACTIVE_NORMAL_11: Isaac.GetItemIdByName("            "),
  ZAZZ_ACTIVE_NORMAL_12: Isaac.GetItemIdByName("             "),
} as const;
