import {
  BoilVariant,
  BoomFlyVariant,
  ChargerSubType,
  ChargerVariant,
  ChubVariant,
  ClottyVariant,
  EntityType,
  GaperVariant,
  GlobinVariant,
  GusherVariant,
  GutsVariant,
  HiveVariant,
  HopperVariant,
  HostVariant,
  KnightVariant,
  LarryJrVariant,
  LeaperVariant,
  MawVariant,
  MrMawVariant,
  MulliganVariant,
  PooterVariant,
  SpittyVariant,
  SubHorfVariant,
  VisVariant,
} from "isaac-typescript-definitions";

/** An enum of EntityIDs which correlate to an NPC. */
// Excluded: Shopkeeper 17, Fireplace 33, Baby 38,
export const NPCID = {
  FROWNING_GAPER: `${EntityType.GAPER}.${GaperVariant.FROWNING_GAPER}.0`,
  GAPER: `${EntityType.GAPER}.${GaperVariant.GAPER}.0`,
  FLAMING_GAPER: `${EntityType.GAPER}.${GaperVariant.FLAMING_GAPER}.0`,
  ROTTEN_GAPER: `${EntityType.GAPER}.${GaperVariant.ROTTEN_GAPER}.0`,
  GUSHER: `${EntityType.GUSHER}.${GusherVariant.GUSHER}.0`,
  PACER: `${EntityType.GAPER}.${GusherVariant.PACER}.0`,
  HORF: `${EntityType.HORF}.${SubHorfVariant.SUB_HORF}.0`,
  TAINTED_HORF: `${EntityType.HORF}.${SubHorfVariant.TAINTED_SUB_HORF}.0`,
  FLY: `${EntityType.FLY}.0.0`,
  POOTER: `${EntityType.POOTER}.${PooterVariant.POOTER}.0`,
  SUPER_POOTER: `${EntityType.POOTER}.${PooterVariant.SUPER_POOTER}.0`,
  TAINTED_POOTER: `${EntityType.POOTER}.${PooterVariant.TAINTED_POOTER}.0`,
  BLOB: `${EntityType.CLOTTY}.${ClottyVariant.BLOB}.0`,
  CLOT: `${EntityType.CLOTTY}.${ClottyVariant.CLOT}.0`,
  CLOTTY: `${EntityType.CLOTTY}.${ClottyVariant.CLOTTY}.0`,
  GRILLED_CLOTTY: `${EntityType.CLOTTY}.${ClottyVariant.GRILLED_CLOTTY}.0`,
  MULLIBOOM: `${EntityType.MULLIGAN}.${MulliganVariant.MULLIBOOM}.0`,
  MULLIGAN: `${EntityType.MULLIGAN}.${MulliganVariant.MULLIGAN}.0`,
  MULLIGOON: `${EntityType.MULLIGAN}.${MulliganVariant.MULLIGOON}.0`,
  ATTACK_FLY: `${EntityType.ATTACK_FLY}.0.0`,
  LARRY_JR: `${EntityType.LARRY_JR}.${LarryJrVariant.LARRY_JR}.0`,
  THE_HOLLOW: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_HOLLOW}.0`,
  THE_SHELL: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_SHELL}.0`,
  TUFF_TWIN: `${EntityType.LARRY_JR}.${LarryJrVariant.TUFF_TWIN}.0`,
  MONSTRO: `${EntityType.MONSTRO}.0.0`,
  MAGGOT: `${EntityType.MAGGOT}.0.0`,
  DROWNED_HIVE: `${EntityType.HIVE}.${HiveVariant.DROWNED_HIVE}.0`,
  HIVE: `${EntityType.HIVE}.${HiveVariant.HIVE}.0`,
  HOLY_MULLIGAN: `${EntityType.HIVE}.${HiveVariant.HOLY_MULLIGAN}.0`,
  TAINTED_MULLIGAN: `${EntityType.HIVE}.${HiveVariant.TAINTED_MULLIGAN}.0`,
  CARRION_PRINCESS: `${EntityType.CHARGER}.${ChargerVariant.CARRION_PRINCESS}.0`,
  CHARGER: `${EntityType.CHARGER}.${ChargerVariant.CHARGER}.${ChargerSubType.CHARGER}`,
  MY_SHADOW_CHARGER: `${EntityType.CHARGER}.${ChargerVariant.CHARGER}.${ChargerSubType.MY_SHADOW}`,
  DANK_CHARGER: `${EntityType.CHARGER}.${ChargerVariant.DANK_CHARGER}.0`,
  DROWNED_CHARGER: `${EntityType.CHARGER}.${ChargerVariant.DROWNED_CHARGER}.0`,
  CURSED_GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.CURSED_GLOBIN}.0`,
  DANK_GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.DANK_GLOBIN}.0`,
  GAZING_GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.GAZING_GLOBIN}.0`,
  GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.GLOBIN}.0`,
  BONE_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.BONE_FLY}.0`,
  BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.BOOM_FLY}.0`,
  DRAGON_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.DRAGON_FLY}.0`,
  DROWNED_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.DROWNED_BOOM_FLY}.0`,
  RED_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.RED_BOOM_FLY}.0`,
  STICK_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.SICK_BOOM_FLY}.0`,
  TAINTED_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.TAINTED_BOOM_FLY}.0`,
  MAW: `${EntityType.MAW}.${MawVariant.MAW}.0`,
  PSYCHIC_MAW: `${EntityType.MAW}.${MawVariant.PSYCHIC_MAW}.0`,
  RED_MAW: `${EntityType.MAW}.${MawVariant.RED_MAW}.0`,
  HARD_HOST: `${EntityType.HOST}.${HostVariant.HARD_HOST}.0`,
  HOST: `${EntityType.HOST}.${HostVariant.HOST}.0`,
  RED_HOST: `${EntityType.HOST}.${HostVariant.RED_HOST}.0`,
  CARRION_QUEEN: `${EntityType.CHUB}.${ChubVariant.CARRION_QUEEN}.0`,
  CHAD: `${EntityType.CHUB}.${ChubVariant.CHAD}.0`,
  CHUB: `${EntityType.CHUB}.${ChubVariant.CHUB}.0`,
  EGGY: `${EntityType.HOPPER}.${HopperVariant.EGGY}.0`,
  HOPPER: `${EntityType.HOPPER}.${HopperVariant.HOPPER}.0`,
  TAINTED_HOPPER: `${EntityType.HOPPER}.${HopperVariant.TAINTED_HOPPER}.0`,
  TRITE: `${EntityType.HOPPER}.${HopperVariant.TRITE}.0`,
  BOIL: `${EntityType.BOIL}.${BoilVariant.BOIL}.0`,
  GUT: `${EntityType.BOIL}.${BoilVariant.GUT}.0`,
  SACK: `${EntityType.BOIL}.${BoilVariant.SACK}.0`,
  SPITTY: `${EntityType.SPITTY}.${SpittyVariant.SPITTY}.0`,
  TAINTED_SPITTY: `${EntityType.SPITTY}.${SpittyVariant.TAINTED_SPITTY}.0`,
  BRAIN: `${EntityType.BRAIN}.0.0`,
  LEAPER: `${EntityType.LEAPER}.${LeaperVariant.LEAPER}.0`,
  STICKY_LEAPER: `${EntityType.LEAPER}.${LeaperVariant.STICKY_LEAPER}.0`,
  MR_MAW: `${EntityType.MR_MAW}.${MrMawVariant.MR_MAW}.0`,
  MR_MAW_HEAD: `${EntityType.MR_MAW}.${MrMawVariant.MR_MAW_HEAD}.0`,
  MR_MAW_NECK: `${EntityType.MR_MAW}.${MrMawVariant.MR_MAW_NECK}.0`,
  MR_RED_MAW: `${EntityType.MR_MAW}.${MrMawVariant.MR_RED_MAW}.0`,
  MR_RED_MAW_HEAD: `${EntityType.MR_MAW}.${MrMawVariant.MR_RED_MAW_HEAD}.0`,
  GURDY: `${EntityType.GURDY}.0.0`,
  CHUBBER: `${EntityType.VIS}.${VisVariant.CHUBBER}.0`,
  CHUBBER_PROJECTILE: `${EntityType.VIS}.${VisVariant.CHUBBER_PROJECTILE}.0`, // ????
  DOUBLE_VIS: `${EntityType.VIS}.${VisVariant.DOUBLE_VIS}.0`,
  SCARRED_DOUBLE_VIS: `${EntityType.VIS}.${VisVariant.SCARRED_DOUBLE_VIS}.0`,
  VIS: `${EntityType.VIS}.${VisVariant.VIS}.0`,
  GUTS: `${EntityType.GUTS}.${GutsVariant.GUTS}.0`,
  SCARRED_GUTS: `${EntityType.GUTS}.${GutsVariant.SCARRED_GUTS}.0`,
  SLOG: `${EntityType.GUTS}.${GutsVariant.SLOG}.0`,
  BLACK_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.BLACK_KNIGHT}.0`,
  BRAINLESS_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.BRAINLESS_KNIGHT}.0`,
  KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.KNIGHT}.0`,
  LOOSE_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.LOOSE_KNIGHT}.0`,
  SELFLESS_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.SELFLESS_KNIGHT}.0`,
} as const;

/** EntityIDs which correlate to an NPC. */
// eslint-disable-next-line @typescript-eslint/no-redeclare
export type NPCID = typeof NPCID[keyof typeof NPCID];
