/** TODO: Change back to Deleted. */

export const PlayerTypeCustom = {
  DELETED_HAPPY99: Isaac.GetPlayerTypeByName("Deleted"),
  DELETED_ILOVEYOU: Isaac.GetPlayerTypeByName("Deleted_ILOVEYOU"),
  DELETED_MORRIS: Isaac.GetPlayerTypeByName("Deleted_MORRIS"),
  DELETED_ZIPBOMBER: Isaac.GetPlayerTypeByName("Deleted_ZIPBOMBER"),
  DELETED_CRYPTOLOCKER: Isaac.GetPlayerTypeByName("Deleted_CRYPTOLOCKER"),
  DELETED_SPYWIPER: Isaac.GetPlayerTypeByName("Deleted_SPYWIPER"),
  DELETED_JERUSALEM: Isaac.GetPlayerTypeByName("Deleted_JERUSALEM"),
  DELETED_HICURDISMOS: Isaac.GetPlayerTypeByName("Deleted_HICURDISMOS"),
  DELETED_VCS: Isaac.GetPlayerTypeByName("Deleted_VCS"),
  DELETED_MYDOOM: Isaac.GetPlayerTypeByName("Deleted_MYDOOM"),
  DELETED_MEMZ: Isaac.GetPlayerTypeByName("Deleted_MEMZ"),
  DELETED_REVETON: Isaac.GetPlayerTypeByName("Deleted_REVETON"),
  DELETED_WANNACRY: Isaac.GetPlayerTypeByName("Deleted_WANNACRY"),
  DELETED_BAGLE: Isaac.GetPlayerTypeByName("Deleted_BAGLE"),
  DELETED_DOZER: Isaac.GetPlayerTypeByName("Deleted_DOZER"),
  DELETED_MYLIFE: Isaac.GetPlayerTypeByName("Deleted_MYLIFE"),
  DELETED_CODE_RED: Isaac.GetPlayerTypeByName("Deleted_CODERED"),
  DELETED_CASINO: Isaac.GetPlayerTypeByName("Deleted_CASINO"),
  DELETED_DREAMWORLD: Isaac.GetPlayerTypeByName("Deleted_DREAMWORLD"),
  T_DELETED_SOPHOS: Isaac.GetPlayerTypeByName("Deleted", true),
  T_DELETED_BATTLEYE: Isaac.GetPlayerTypeByName("Deleted_BATTLEYE", true),
} as const;
