export const SoundEffectCustom = {
  BITFLIP_IN: Isaac.GetSoundIdByName("thedeleted_Glitch In"),
  BITFLIP_OUT: Isaac.GetSoundIdByName("thedeleted_Glitch Out"),
  ROLL_DICE: Isaac.GetSoundIdByName("thedeleted_diceroll"),
  TRASH: Isaac.GetSoundIdByName("thedeleted_Trash"),
  PC_LOG_IN: Isaac.GetSoundIdByName("thedeleted_pc_login"),
  KISS: Isaac.GetSoundIdByName("thedeleted_kiss"),
  ILOVEYOU_GRUNT: Isaac.GetSoundIdByName("thedeleted_iloveyou_hurt"),

  /** Voiceover */
  VO_ANIMAL: Isaac.GetSoundIdByName("thedeleted_voiceover_Animal"),
  VO_ILOVEYOU: Isaac.GetSoundIdByName("thedeleted_voiceover_ILoveYou"),
  VO_SPYWIPER: Isaac.GetSoundIdByName("thedeleted_voiceover_Spywiper"),
  VO_REVETON: Isaac.GetSoundIdByName("thedeleted_voiceover_Reveton"),
  VO_MYDOOM: Isaac.GetSoundIdByName("thedeleted_voiceover_MyDoom"),
  VO_VCS: Isaac.GetSoundIdByName("thedeleted_voiceover_VCS"),
  VO_ZIPBOMBER: Isaac.GetSoundIdByName("thedeleted_voiceover_ZipBomber"),
  VO_MYLIFE: Isaac.GetSoundIdByName("thedeleted_voiceover_MyLife"),
  VO_MORRIS: Isaac.GetSoundIdByName("thedeleted_voiceover_Morris"),
  VO_MEMZ: Isaac.GetSoundIdByName("thedeleted_voiceover_Memz"),
  VO_MADMAN: Isaac.GetSoundIdByName("thedeleted_voiceover_MadMan"),
  VO_JERUSALEM: Isaac.GetSoundIdByName("thedeleted_voiceover_Jerusalem"),
  VO_HICURDISMOS: Isaac.GetSoundIdByName("thedeleted_voiceover_Hicurdismos"),
  VO_HAPPY99: Isaac.GetSoundIdByName("thedeleted_voiceover_Happy99"),
  VO_DREAMWORLD: Isaac.GetSoundIdByName("thedeleted_voiceover_Dreamworld"),
  VO_DOZER: Isaac.GetSoundIdByName("thedeleted_voiceover_Dozer"),
  VO_CRYPTOLOCKER: Isaac.GetSoundIdByName("thedeleted_voiceover_CryptoLocker"),
  VO_CODERED: Isaac.GetSoundIdByName("thedeleted_voiceover_CodeRed"),
  VO_YOUAREANIDIOT: Isaac.GetSoundIdByName(
    "thedeleted_voiceover_YouAreAnIdiot",
  ),
  VO_BAGLE1: Isaac.GetSoundIdByName("thedeleted_voiceover_Bagle1"),
  VO_BAGLE2: Isaac.GetSoundIdByName("thedeleted_voiceover_Bagle2"),
  VO_CREEPER: Isaac.GetSoundIdByName("thedeleted_voiceover_Creeper"),
} as const;
