import { EntityType, PickupVariant } from "isaac-typescript-definitions";
import type { WeightedArray } from "isaacscript-common";
import { ReadonlySet } from "isaacscript-common";
import { PickupID } from "../enums/data/ID/PickupID";

/**
 * PickupVariants that have their subType auto-generated upon game start, depending on the number
 * and order of mods enabled. These pickups' subTypes can be found using their corresponding
 * ItemConfig class.
 */
export const PICKUP_VARIANTS_WITH_AUTOGENERATED_SUBTYPES = new ReadonlySet([
  PickupVariant.COLLECTIBLE,
  PickupVariant.TRINKET,
  PickupVariant.PILL,
  PickupVariant.CARD,
]);

/** All non-Modded Souls and most modded Souls should have their name prefixed with this. */
export const SOUL_PREFIX = "Soul of";

/** This PickupID refers to a random pickup decided by the game. */
export const RANDOM_PICKUP_ID =
  `${EntityType.PICKUP}${PickupVariant.NULL}.0` as PickupID;

// eslint-disable-next-line isaacscript/require-capital-read-only
export const RANDOM_SOFT_NON_MODDED_SOUL_PICKUP_ID_SPREAD = [
  [PickupID.SOUL_OF_APOLLYON, 1],
] as WeightedArray<PickupID>;

// eslint-disable-next-line isaacscript/require-capital-read-only
export const RANDOM_SOFT_NON_MODDED_RUNE_PICKUP_ID_SPREAD = [
  [PickupID.JERA_RUNE, 1],
] as WeightedArray<PickupID>;

// eslint-disable-next-line isaacscript/require-capital-read-only
export const RANDOM_SOFT_NON_MODDED_MISCELLANEOUS_PICKUP_ID_SPREAD = [
  [PickupID.MOMS_BED, 1],
] as WeightedArray<PickupID>;
