import { ReadonlyMap } from "isaacscript-common";

export const ENTITIES_MAP = new ReadonlyMap<string, [string, number]>([
  ["MERN", ["Mern", 0]],
  ["FIEND_MINION", ["Fiend Minion", 1]],
  ["FIEND_MINION_IMMORAL", ["Fiend Minion (Immoral)", 2]],
  ["FIEND_MINION_HALF_IMMORAL", ["Fiend Minion (Half Immoral)", 3]],
  ["FIEND_MINION_HALF_ETERNAL", ["Fiend Minion (Half Eternal)", 4]],
  ["FIEND_MINION_GOLD", ["Fiend Minion (Gold)", 5]],
  ["FIEND_MINION_RED", ["Fiend Minion (Red)", 6]],
  ["FIEND_MINION_HALF_RED", ["Fiend Minion (Half Red)", 7]],
  ["FIEND_MINION_ROTTEN", ["Fiend Minion (Rotten)", 8]],
  ["FIEND_MINION_SOUL", ["Fiend Minion (Soul)", 9]],
  ["FIEND_MINION_HALF_SOUL", ["Fiend Minion (Half Soul)", 10]],
  ["FIEND_MINION_EGG", ["Fiend Minion Egg", 1]],
  ["FIEND_MINION_EFFECT", ["Fiend Minion (Effect)", 0]],
  ["FIEND_MINION_EFFECT", ["Fiend Minion (Effect)", 10]],
  ["MINING_MACHINE", ["Mining Machine", 0]],
  ["BISMUTH_BEGGAR", ["Bismuth Beggar", 0]],
  ["SOURPUSS", ["Sourpuss", 0]],
  ["UNFINISHED_GOLEM", ["Unfinished Golem", 0]],
  ["GEODE_GOLEM", ["Geode Golem", 0]],
  ["BABI", ["Babi", 0]],
  ["MIDARIZER", ["Midarizer", 0]],
  ["SWEETPUSS", ["Sweetpuss", 0]],
  ["POKER_TABLE", ["Poker Table", 0]],
  ["BLACKSMITH", ["Blacksmith", 0]],
  ["ZODIAC_BEGGAR", ["Zodiac Beggar", 0]],
  ["ROBOT_TELLER", ["Robot Teller", 0]],
  ["EVIL_BEGGAR", ["Evil Beggar", 0]],
  ["FAKE_BEGGAR", ["Fake Beggar", 0]],
  ["DEALER", ["Dealer", 0]],
  ["CELL_GAME", ["Cell Game", 0]],
  ["HUG_BEGGAR", ["Hug Beggar", 0]],
  ["COSPLAY_BEGGAR", ["Cosplay Beggar", 0]],
  ["PHONE_BOOTH", ["Phone Booth", 0]],
  ["GOLDEN_SLOT_MACHINE", ["Golden Slot Machine", 0]],
  ["JUKEBOX", ["Jukebox", 0]],
  ["VENDING_MACHINE_VANILLA", ["Vending Machine (Vanilla)", 0]],
  ["VENDING_MACHINE_FIEND_FOLIO", ["Vending Machine (Fiend Folio)", 0]],
  ["DICE_BAG", ["Dice Bag", 0]],
  ["LIL_FIEND", ["Li'l Fiend", 0]],
  ["BABY_CRATER", ["Baby Crater", 0]],
  ["MAMA_SPOOTER", ["Mama Spooter", 0]],
  ["RANDY_THE_SNAIL", ["Randy The Snail", 0]],
  ["MERN_L1", ["Mern L1", 0]],
  ["MERN_L2", ["Mern L2", 0]],
  ["MERN_L3", ["Mern L3", 0]],
  ["MERN_L4", ["Mern L4", 0]],
  ["PEACH_CREEP", ["Peach Creep", 0]],
  ["ATTACK_SKUZZ", ["Attack Skuzz", 0]],
  ["FLEA_OF_MELTDOWN", ["Flea of Meltdown", 1]],
  ["FLEA_OF_DELUGE", ["Flea of Deluge", 2]],
  ["FLEA_OF_POLLUTION", ["Flea of Pollution", 3]],
  ["FLEA_OF_PROPAGANDA", ["Flea of Propaganda", 4]],
  ["GRABBER", ["Grabber", 0]],
  ["GORGON", ["Gorgon", 0]],
  ["JONATHAN_DEIMOS_FAMILIAR", ["Jonathan (Deimos familiar)", 0]],
  ["PET_ROCK", ["Pet Rock", 0]],
  ["LIL_MINX", ["Li'l Minx", 0]],
  ["OPHIUCHUS_SERPENT", ["Ophiuchus Serpent", 0]],
  ["BABY_ORB", ["Baby Orb", 0]],
  ["LIL_LAMB", ["Lil' Lamb", 0]],
  ["LIL_LAMB_BODY", ["Lil' Lamb Body", 1]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 0]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 1]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 2]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 3]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 4]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 5]],
  ["SIBLING_SYL", ["Sibling Syl", 0]],
  ["GREG", ["Greg", 0]],
  ["ORANGEBOOMFLY", ["OrangeBoomFly", 0]],
  ["BABY_ROCK", ["Baby Rock", 0]],
  ["D3", ["D3", 0]],
  ["WIMPY_BRO", ["Wimpy Bro", 0]],
  ["ROBOBABY_30", ["Robo-Baby 3.0", 0]],
  ["NYX_CAST_GEM", ["Nyx Cast Gem", 0]],
  ["NYX_BLADE_RIFT", ["Nyx Blade Rift", 0]],
  ["STAR_SAPPHIRE_ORBITAL", ["Star Sapphire Orbital", 0]],
  ["SUN_SHARD_FAMILIAR", ["Sun Shard Familiar", 0]],
  ["TIGERS_EYE", ["Tiger's Eye", 0]],
  ["SACK_OF_SPICY", ["Sack of Spicy", 0]],
  ["HATRED", ["Hatred", 0]],
  ["RED_GRABBER_HAND", ["Red Grabber Hand", 0]],
  ["LIL_CLUTCH", ["Lil Clutch", 0]],
  ["PET_PEEVE", ["Pet Peeve", 0]],
  ["BAG_OF_BOBBIES", ["Bag of Bobbies", 0]],
  ["FRAGILE_BOBBY", ["Fragile Bobby", 0]],
  ["MORBID_CHUNK", ["Morbid Chunk", 0]],
  ["LITTLE_FAIRY_FLY", ["Little Fairy Fly", 0]],
  ["ROUND_FAIRY_FLY", ["Round Fairy Fly", 0]],
  ["BIG_FAIRY_FLY", ["Big Fairy Fly", 0]],
  ["WORMHOLE_ROCK_PORTAL", ["Wormhole Rock Portal", 0]],
  ["HONEYFOX", ["HoneyFox", 0]],
  ["HONEYFOX_WORM", ["HoneyFox (Worm)", 0]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 100]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 101]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 102]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 103]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 104]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 105]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 106]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 107]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 108]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 109]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 110]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 111]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 112]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 113]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 114]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 115]],
  ["FF_BOOK_HELPER", ["FF Book Helper", 116]],
  ["TOKEN_BAG", ["Token Bag", 0]],
  ["LITHOPEDIAN_FAMILIAR", ["Lithopedian Familiar", 0]],
  ["BRICKMIN", ["Brickmin", 0]],
  ["BRICKMIN", ["Brickmin", 1]],
  ["BRICKMIN", ["Brickmin", 2]],
  ["DIP_FAMILIAR_DROP", ["Dip Familiar (Drop)", 666]],
  ["DIP_FAMILIAR_CURSED", ["Dip Familiar (Cursed)", 667]],
  ["DIP_FAMILIAR_BEE", ["Dip Familiar (Bee)", 668]],
  ["DIP_FAMILIAR_PLATINUM", ["Dip Familiar (Platinum)", 669]],
  ["DIP_FAMILIAR_SPIDER", ["Dip Familiar (Spider)", 670]],
  ["DIP_FAMILIAR_EVIL", ["Dip Familiar (Evil)", 671]],
  ["DIP_FAMILIAR_DAD", ["Dip Familiar (Dad)", 672]],
  ["DIP_FAMILIAR_FUZZY", ["Dip Familiar (Fuzzy)", 673]],
  ["COPPER_BOMB_PICKUP", ["Copper Bomb (pickup)", 923]],
  ["DOUBLE_COPPER_BOMB_PICKUP", ["Double Copper Bomb (pickup)", 924]],
  ["MIXED_DOUBLE_BOMB_PICKUP", ["Mixed Double Bomb (pickup)", 925]],
  ["COPPER_TROLL_BOMB", ["Copper Troll Bomb", 160]],
  ["NUGGET_BOMB", ["Nugget Bomb", 0]],
  ["LOCUST_BOMB", ["Locust Bomb", 0]],
  ["SLIPPY_BOMB", ["Slippy Bomb", 0]],
  ["COPPER_BOMB", ["Copper Bomb", 0]],
  ["COPPER_NUGGET_BOMB", ["Copper Nugget Bomb", 0]],
  ["COPPER_LOCUST_BOMB", ["Copper Locust Bomb", 0]],
  ["COPPER_SLIPPY_BOMB", ["Copper Slippy Bomb", 0]],
  ["BRIDGE_BOMB", ["Bridge Bomb", 0]],
  ["COPPER_BRIDGE_BOMB", ["Copper Bridge Bomb", 0]],
  ["COPPER_TROLL_BOMB_REGULARISED", ["Copper Troll Bomb (Regularised)", 0]],
  ["ORBITING_FIREBALL", ["Orbiting Fireball", 0]],
  ["BLUE_PUZZLE_KEY", ["Blue Puzzle Key", 0]],
  ["GREEN_PUZZLE_KEY", ["Green Puzzle Key", 1]],
  ["RED_PUZZLE_KEY", ["Red Puzzle Key", 2]],
  ["BLOOD_SACK", ["Blood Sack", 0]],
  ["TRASH_BAG", ["Trash Bag", 10]],
  ["52_DECK", ["52 Deck", 11]],
  ["CURSED_PENNY", ["Cursed Penny", 213]],
  ["HAUNTED_PENNY", ["Haunted Penny", 214]],
  ["HONEY_PENNY", ["Honey Penny", 215]],
  ["GOLDEN_CURSED_PENNY", ["Golden Cursed Penny", 216]],
  ["LEGO_STUD", ["Lego Stud", 217]],
  ["SPICY_KEY", ["Spicy Key", 179]],
  ["SUPER_SPICY_KEY", ["Super Spicy Key", 180]],
  ["CHARGED_SPICY_KEY", ["Charged Spicy Key", 181]],
  ["SPICY_KEY_BOX", ["Spicy Key (Box)", 182]],
  ["CHARGED_SPICY_KEY_BOX", ["Charged Spicy Key (Box)", 183]],
  ["SUPER_SPICY_KEY_BOX", ["Super Spicy Key (Box)", 184]],
  ["SPICY_KEY_PERM", ["Spicy Key (Perm)", 185]],
  ["SUPER_SPICY_KEY_PERM", ["Super Spicy Key (Perm)", 186]],
  ["CHARGED_SPICY_KEY_PERM", ["Charged Spicy Key (Perm)", 187]],
  ["GOLDEN_MEDALLION", ["Golden Medallion", 0]],
  ["FIENDISH_CAKE", ["Fiendish Cake", 114]],
  ["TOKEN_PICKUP", ["Token (Pickup)", 0]],
  ["FIREWORK_BATTERY", ["Firework Battery", 0]],
  ["VIRTUOUS_BATTERY", ["Virtuous Battery", 0]],
  ["POTATO_BATTERY", ["Potato Battery", 0]],
  ["CURSED_BATTERY", ["Cursed Battery", 0]],
  ["BLUE_PRISM_SHARD", ["Blue Prism Shard", 0]],
  ["GREEN_PRISM_SHARD", ["Green Prism Shard", 1]],
  ["PURPLE_PRISM_SHARD", ["Purple Prism Shard", 2]],
  ["RAINBOW_PRISM_SHARD", ["Rainbow Prism Shard", 3]],
  ["RED_PRISM_SHARD", ["Red Prism Shard", 4]],
  ["YELLOW_PRISM_SHARD", ["Yellow Prism Shard", 5]],
  ["PILL_CYANIDE", ["Pill Cyanide", 960]],
  ["PILL_GOLD_CYANIDE", ["Pill Gold Cyanide", 961]],
  ["PILL_BLACKPURPLE", ["Pill Black-Purple", 101]],
  ["PILL_PURPLEORANGE", ["Pill Purple-Orange", 102]],
  ["PILL_BLUEYELLOW", ["Pill Blue-Yellow", 103]],
  ["PILL_BLUESILVER", ["Pill Blue-Silver", 104]],
  ["PILL_DOTSVIOLET", ["Pill Dots-Violet", 105]],
  ["PILL_MAROONSHADOW", ["Pill Maroon-Shadow", 106]],
  ["PILL_DOTSLIME", ["Pill Dots-Lime", 107]],
  ["PILL_EMERALDBEIGE", ["Pill Emerald-Beige", 108]],
  ["PILL_BLACKBLACK", ["Pill Black-Black", 109]],
  ["PILL_REDRED", ["Pill Red-Red", 110]],
  ["PILL_DOTSBLUE", ["Pill Dots-Blue", 111]],
  ["PILL_DOTSPINK", ["Pill Dots-Pink", 112]],
  ["PILL_IVORYBYZANTIUM", ["Pill Ivory-Byzantium", 113]],
  ["PILL_WHITEORANGE", ["Pill White-Orange", 114]],
  ["PILL_DOTSBLACK", ["Pill Dots-Black", 115]],
  ["PILL_RAINBOWGREY", ["Pill Rainbow-Grey", 116]],
  ["PILL_GREYTEAL", ["Pill Grey-Teal", 117]],
  ["PILL_DOTSYELLOW", ["Pill Dots-Yellow", 118]],
  ["PILL_YELLOWCOW", ["Pill Yellow-Cow", 119]],
  ["PILL_TAUPEOFFBLACK", ["Pill Taupe-Offblack", 120]],
  ["HORSE_PILL_CYANIDE", ["Horse Pill Cyanide", 3008]],
  ["HORSE_PILL_GOLD_CYANIDE", ["Horse Pill Gold Cyanide", 3009]],
  ["HORSE_PILL_BLACKPURPLE", ["Horse Pill Black-Purple", 2149]],
  ["HORSE_PILL_PURPLEORANGE", ["Horse Pill Purple-Orange", 2150]],
  ["HORSE_PILL_BLUEYELLOW", ["Horse Pill Blue-Yellow", 2151]],
  ["HORSE_PILL_BLUESILVER", ["Horse Pill Blue-Silver", 2152]],
  ["HORSE_PILL_DOTSVIOLET", ["Horse Pill Dots-Violet", 2153]],
  ["HORSE_PILL_MAROONSHADOW", ["Horse Pill Maroon-Shadow", 2154]],
  ["HORSE_PILL_DOTSLIME", ["Horse Pill Dots-Lime", 2155]],
  ["HORSE_PILL_EMERALDBEIGE", ["Horse Pill Emerald-Beige", 2156]],
  ["HORSE_PILL_BLACKPILL", ["Horse Pill Black-Pill", 2157]],
  ["HORSE_PILL_REDRED", ["Horse Pill Red-Red", 2158]],
  ["HORSE_PILL_DOTSBLUE", ["Horse Pill Dots-Blue", 2159]],
  ["HORSE_PILL_DOTSPINK", ["Horse Pill Dots-Pink", 2160]],
  ["HORSE_PILL_IVORYBYZANTIUM", ["Horse Pill Ivory-Byzantium", 2161]],
  ["HORSE_PILL_WHITEORANGE", ["Horse Pill White-Orange", 2162]],
  ["HORSE_PILL_SAGEBURGUNDY", ["Horse Pill Sage-Burgundy", 2163]],
  ["HORSE_PILL_RAINBOWGREY", ["Horse Pill Rainbow-Grey", 2164]],
  ["HORSE_PILL_GREYTEAL", ["Horse Pill Grey-Teal", 2165]],
  ["HORSE_PILL_DOTSYELLOW", ["Horse Pill Dots-Yellow", 2166]],
  ["HORSE_PILL_YELLOWCOW", ["Horse Pill Yellow-Cow", 2167]],
  ["HORSE_PILL_TAUPEOFFBLACK", ["Horse Pill Taupe-Offblack", 2168]],
  ["GLASS_D6", ["Glass D6", 960]],
  ["GLASS_D4", ["Glass D4", 961]],
  ["GLASS_D8", ["Glass D8", 962]],
  ["GLASS_D100", ["Glass D100", 963]],
  ["GLASS_D10", ["Glass D10", 964]],
  ["GLASS_D20", ["Glass D20", 965]],
  ["GLASS_D12", ["Glass D12", 966]],
  ["GLASS_SPINDOWN", ["Glass Spindown", 1009]],
  ["GLASS_AZURITE_SPINDOWN", ["Glass Azurite Spindown", 1012]],
  ["CALLING_CARD", ["Calling Card", 967]],
  ["GROTTO_BEAST", ["Grotto Beast", 968]],
  ["GLASS_D2", ["Glass D2", 969]],
  ["DOWNLOAD_FAILURE", ["Download Failure", 970]],
  ["PUZZLE_PIECE", ["Puzzle Piece", 971]],
  ["STORAGE_BATTERY_0", ["Storage Battery 0", 972]],
  ["STORAGE_BATTERY_1", ["Storage Battery 1", 973]],
  ["STORAGE_BATTERY_2", ["Storage Battery 2", 974]],
  ["STORAGE_BATTERY_3", ["Storage Battery 3", 975]],
  ["CORRODED_BATTERY_0", ["Corroded Battery 0", 976]],
  ["CORRODED_BATTERY_1", ["Corroded Battery 1", 977]],
  ["CORRODED_BATTERY_2", ["Corroded Battery 2", 978]],
  ["CORRODED_BATTERY_3", ["Corroded Battery 3", 979]],
  ["DYING_BATTERY", ["Dying Battery", 0]],
  ["DOWNLOAD_FAILURE", ["Download Failure", 980]],
  ["SOUL_OF_FIEND", ["Soul of Fiend", 981]],
  ["SOUL_OF_GOLEM", ["Soul of Golem", 982]],
  ["SOUL_OF_FRIEND", ["Soul of Friend", 983]],
  ["SOUL_OF_SLIPPY", ["Soul of Slippy", 984]],
  ["SOUL_OF_RANDOM", ["Soul of Random", 985]],
  ["PLAGUE_OF_DECAY", ["Plague of Decay", 986]],
  ["SMALL_CONTRABAND", ["Small Contraband", 991]],
  ["DEFUSE", ["Defuse", 987]],
  ["POT_OF_GREED", ["Pot of Greed", 995]],
  ["REVERSE_PLAYING_CARD", ["Reverse Playing Card", 988]],
  ["BLUE_PLAYING_CARD", ["Blue Playing Card", 989]],
  ["PHASE_10_CARD", ["Phase 10 Card", 990]],
  ["MINOR_ARCANA_CARD", ["Minor Arcana Card", 992]],
  ["MISPRINTED_PLAYING_CARD", ["Misprinted Playing Card", 993]],
  ["FRIENDLYMON_CARD", ["Friendlymon Card", 994]],
  ["GREEN_HOUSE", ["Green House", 996]],
  ["CARDJITSU_CARD", ["Card-Jitsu Card", 997]],
  ["COOL_PHOTO", ["Cool Photo", 998]],
  ["GREEN_HOUSE", ["Green House", 999]],
  ["TREASURE_DISC", ["Treasure Disc", 1000]],
  ["SHOP_DISC", ["Shop Disc", 1001]],
  ["BOSS_DISC", ["Boss Disc", 1002]],
  ["SECRET_DISC", ["Secret Disc", 1003]],
  ["DEVIL_DISC", ["Devil Disc", 1004]],
  ["ANGEL_DISC", ["Angel Disc", 1005]],
  ["PLANETARIUM_DISC", ["Planetarium Disc", 1006]],
  ["CHAOS_DISC", ["Chaos Disc", 1014]],
  ["BROKEN_DISC", ["Broken Disc", 1007]],
  ["TAINTED_TREASURE_DISC", ["Tainted Treasure Disc", 1016]],
  ["BLANK_LETTER_TILE", ["Blank Letter Tile", 1008]],
  ["HORSE_PUSHPOP", ["Horse Push-Pop", 1010]],
  ["REVERSE_MAGIC_CARD", ["Reverse Magic Card", 1011]],
  ["TOP_HAT", ["Top Hat", 1013]],
  ["GIFT_CARD", ["Gift Card", 1015]],
  ["STUD", ["Stud", 1017]],
  ["STUD_2", ["Stud (2)", 1018]],
  ["STUD_3", ["Stud (3)", 1019]],
  ["STUD_4", ["Stud (4)", 1020]],
  ["STUD_5", ["Stud (5)", 1021]],
  ["STUD_6", ["Stud (6)", 1022]],
  ["CHRISTMAS_CRACKER", ["Christmas Cracker", 1023]],
  ["BLUE_KEYGHOST", ["Blue Keyghost", 0]],
  ["GREEN_KEYGHOST", ["Green Keyghost", 0]],
  ["RED_KEYGHOST", ["Red Keyghost", 0]],
  ["BLUE_LOCK", ["Blue Lock", 0]],
  ["GREEN_LOCK", ["Green Lock", 0]],
  ["RED_LOCK", ["Red Lock", 0]],
  ["GRAY_LOCK", ["Gray Lock", 0]],
  ["BLUE_CHAIN_LOCK", ["Blue Chain Lock", 0]],
  ["GREEN_CHAIN_LOCK", ["Green Chain Lock", 0]],
  ["RED_CHAIN_LOCK", ["Red Chain Lock", 0]],
  ["GRAY_CHAIN_LOCK", ["Gray Chain Lock", 0]],
  ["FIRE_POT", ["Fire Pot", 0]],
  ["LILY_PAD", ["Lily Pad", 0]],
  ["HALF_BLACK_HEART_FIEND_FOLIO", ["Half Black Heart (Fiend Folio)", 0]],
  ["BLENDED_BLACK_HEART_FIEND_FOLIO", ["Blended Black Heart (Fiend Folio)", 0]],
  ["IMMORAL_HEART", ["Immoral Heart", 0]],
  ["HALF_IMMORAL_HEART", ["Half Immoral Heart", 0]],
  ["BLENDED_IMMORAL_HEART", ["Blended Immoral Heart", 0]],
  ["MORBID_HEART", ["Morbid Heart", 0]],
  ["TWOTHIRDS_MORBID_HEART", ["Two-Thirds Morbid Heart", 0]],
  ["THIRD_MORBID_HEART", ["Third Morbid Heart", 0]],
  ["IMMORAL_BLOOD_BABY", ["Immoral Blood Baby", 920]],
  ["MORBID_BLOOD_BABY", ["Morbid Blood Baby", 921]],
  ["SUPER_TNT", ["Super TNT", 0]],
  ["WATER_TNT", ["Water TNT", 0]],
  ["BUTTERY_COMPOST_BIN", ["Buttery Compost Bin", 0]],
  ["GASSY_COMPOST_BIN", ["Gassy Compost Bin", 1]],
  ["SCENTED_COMPOST_BIN", ["Scented Compost Bin", 2]],
  ["UNSTABLE_COMPOST_BIN", ["Unstable Compost Bin", 3]],
  ["REHEATED_CHEST", ["Reheated Chest", 0]],
  ["SHOP_CHEST", ["Shop Chest", 0]],
  ["DIRE_CHEST", ["Dire Chest", 0]],
  ["DIRE_CHESTOPEN", ["Dire Chest(Open)", 1]],
  ["GLASS_CHEST", ["Glass Chest", 0]],
  ["FORTUNE_COOKIE_TEAR", ["Fortune Cookie Tear", 0]],
  ["HOMING_AMULET_TEAR", ["Homing Amulet Tear", 0]],
  ["HOMING_AMULET_BLOOD_TEAR", ["Homing Amulet Blood Tear", 0]],
  ["FROG_TEAR", ["Frog Tear", 0]],
  ["FROG_BLOOD_TEAR", ["Frog Blood Tear", 0]],
  ["PIN_TEAR", ["Pin Tear", 0]],
  ["PIN_BLOOD_TEAR", ["Pin Blood Tear", 0]],
  ["D10_TEAR", ["D10 Tear", 0]],
  ["M90_BULLET_TEAR", ["M90 Bullet Tear", 0]],
  ["PRANK_COOKIE_TEAR", ["Prank Cookie Tear", 0]],
  ["BOOMERANG_RIB_TEAR", ["Boomerang Rib Tear", 0]],
  ["BRICK_TEAR", ["Brick Tear", 0]],
  ["FIREWORK_ROCKET", ["Firework Rocket", 0]],
  ["CHUBBER_TEAR", ["Chubber Tear", 0]],
  ["MODEL_ROCKET_TEAR", ["Model Rocket Tear", 0]],
  ["EMOJI_TEAR", ["Emoji Tear", 0]],
  ["LEMON_MISHAP_TEAR", ["Lemon Mishap Tear", 0]],
  ["MULTIEUCLIDEAN_TEAR", ["Multi-Euclidean Tear", 0]],
  ["GOLEMS_AR_BULLET_TEAR", ["Golem's AR Bullet Tear", 0]],
  ["HORNCOB_PILL_TEAR", ["Horncob Pill Tear", 0]],
  ["LAWN_DART_TEAR", ["Lawn Dart Tear", 0]],
  ["POCKET_ROCKIT_TEAR", ["Pocket Rock-it Tear", 0]],
  ["FORTUNE_COOKIE_PARTICLE", ["Fortune Cookie Particle", 920]],
  ["MODEL_ROCKET_PARTICLE", ["Model Rocket Particle", 921]],
  ["TAR_BUBBLE", ["Tar Bubble", 0]],
  ["SPIDER_EGG", ["Spider Egg", 1]],
  ["BUBBLE_TINY", ["Bubble (Tiny)", 0]],
  ["BUBBLE_SMALL", ["Bubble (Small)", 1]],
  ["BUBBLE_MEDIUM", ["Bubble (Medium)", 2]],
  ["BUBBLE_LARGE", ["Bubble (Large)", 3]],
  ["BUBBLE_FLY", ["Bubble (Fly)", 4]],
  ["BUBBLE_SPIDER", ["Bubble (Spider)", 5]],
  ["BUBBLE_EXPLOSIVE", ["Bubble (Explosive)", 6]],
  ["BUBBLE_SMALL_WATERY", ["Bubble (Small watery)", 7]],
  ["BUBBLE_MEDIUM_WATERY", ["Bubble (Medium watery)", 8]],
  ["BUBBLE_LARGE_WATERY", ["Bubble (Large watery)", 9]],
  ["BUBBLE_ISOPOLY", ["Bubble (Isopoly)", 10]],
  ["FLY_BUNDLE", ["Fly Bundle", 0]],
  ["NIMBUS_CLOUD", ["Nimbus Cloud", 0]],
  ["JAWBONE_CORPSE", ["Jawbone Corpse", 0]],
  ["BONE_ROCKET", ["Bone Rocket", 0]],
  ["STINGER_PROJECTILE", ["Stinger Projectile", 0]],
  ["HOMING_STINGER_PROJECTILE", ["Homing Stinger Projectile", 1]],
  ["RETURNING_STINGER_PROJECTILE", ["Returning Stinger Projectile", 2]],
  ["SPORE_PROJECTILE", ["Spore Projectile", 0]],
  ["NERVE_CLUSTER", ["Nerve Cluster", 0]],
  ["FLYING_MAGGOT", ["Flying Maggot", 0]],
  ["LVL2_SPIDER_WAITING", ["lvl2 Spider (Waiting)", 0]],
  ["TICKING_SPIDER_WAITING", ["Ticking Spider (Waiting)", 1]],
  ["BABY_LONG_LEGS_WAITING", ["Baby Long Legs (Waiting)", 2]],
  ["SMALL_BABY_LONG_LEGS_WAITING", ["Small Baby Long Legs (Waiting)", 3]],
  ["CRAZY_LONG_LEGS_WAITING", ["Crazy Long Legs (Waiting)", 4]],
  ["SMALL_CRAZY_LONG_LEGS_WAITING", ["Small Crazy Long Legs (Waiting)", 5]],
  ["FULL_SPIDER_WAITING", ["Full Spider (Waiting)", 6]],
  ["RIDERS_SCYTHE", ["Rider's Scythe", 0]],
  ["HOLLOW_KNIGHT_PROJECTILE", ["Hollow Knight Projectile", 0]],
  ["SPARKLY_CROSS", ["Sparkly Cross", 0]],
  ["TECH_SHOT", ["Tech shot", 10]],
  ["OWL_STAR", ["Owl Star", 20]],
  ["GARY", ["Gary", 0]],
  ["FLOATING_SPORE", ["Floating Spore", 0]],
  ["ROUND_WORM_WAITING", ["Round Worm (Waiting)", 1]],
  ["NIGHTCRAWLER_WAITING", ["Nightcrawler (Waiting)", 2]],
  ["ULCER_WAITING", ["Ulcer (Waiting)", 3]],
  ["ROUNDY_WAITING", ["Roundy (Waiting)", 4]],
  ["TUBE_WORM_WAITING", ["Tube Worm (Waiting)", 5]],
  ["PARABITE_WAITING", ["Parabite (Waiting)", 6]],
  ["SCARRED_PARABITE_WAITING", ["Scarred Parabite (Waiting)", 7]],
  ["BONE_WORM_WAITING", ["Bone Worm (Waiting)", 8]],
  ["DRINK_WORM_WAITING", ["Drink Worm (Waiting)", 9]],
  ["LUMP_WAITING", ["Lump (Waiting)", 10]],
  ["FRED_WAITING", ["Fred (Waiting)", 11]],
  ["WEAVER_WAITING", ["Weaver (Waiting)", 12]],
  ["WEAVER_SRWAITING", ["Weaver Sr.(Waiting)", 13]],
  ["PIN_WAITING", ["Pin (Waiting)", 14]],
  ["SCOLEX_WAITING", ["Scolex (Waiting)", 15]],
  ["FRAIL_WAITING", ["Frail (Waiting)", 16]],
  ["KP_WAITING", ["KP (Waiting)", 17]],
  ["BUNKER_WORM_WAITING", ["Bunker Worm (Waiting)", 18]],
  ["DRUNK_WORM_WAITING", ["Drunk Worm (Waiting)", 19]],
  ["MEGA_HAEMOLACRIA_PROJECTILE", ["Mega Haemolacria Projectile", 0]],
  ["HORSE_PROJECTILE", ["Horse Projectile", 0]],
  ["BONE_CROSS", ["Bone Cross", 0]],
  ["CHAIN_BALL", ["Chain Ball", 0]],
  ["STERNUM_RIB", ["Sternum Rib", 0]],
  ["KEY_PROJECTILE", ["Key Projectile", 0]],
  ["PSYEG", ["Psyeg", 0]],
  ["AMNIOTIC_SAC", ["Amniotic Sac", 0]],
  ["MISCARRIAGE", ["Miscarriage", 0]],
  ["DAVY_CROCKETT", ["Davy Crockett", 0]],
  ["BARREL_OF_NUCLEAR_WASTE", ["Barrel of Nuclear Waste", 0]],
  ["SPIDER_PROJECTILE", ["Spider Projectile", 0]],
  ["GELATINOUS_MINE", ["Gelatinous Mine", 0]],
  ["SKULL_SHOT", ["Skull Shot", 0]],
  ["DANGEROUS_DISC", ["Dangerous Disc", 0]],
  ["DANGEROUS_DISC_GUIDE", ["Dangerous Disc Guide", 0]],
  ["POISON_CLOUD_MAKER", ["Poison Cloud Maker", 0]],
  ["DEBUFF_PROJECTILE", ["Debuff Projectile", 0]],
  ["HITCHERS_PITCHFORK", ["Hitcher's Pitchfork", 0]],
  ["FF_CUSTOM_HITBOX", ["FF Custom Hitbox", 0]],
  ["FF_MEMBER_CARD_RELOCATOR", ["FF Member Card Relocator", 0]],
  ["BACKDROP_REPLACER", ["Backdrop Replacer", 0]],
  ["RED_RAMBLEPOINT", ["Red Ramblepoint", 0]],
  ["BLUE_RAMBLEPOINT", ["Blue Ramblepoint", 0]],
  ["BABY_SPIDER_EXPLOSION", ["Baby Spider Explosion", 7000]],
  ["CREEP_GUNPOWDER", ["Creep (Gunpowder)", 7000]],
  ["CREEP_VOLATILE_GUNPOWDER", ["Creep (Volatile Gunpowder)", 7001]],
  ["ANTIBIRTH_DIRTPILE", ["Antibirth Dirtpile", 7002]],
  ["WEAVER_DIRTPILE", ["Weaver Dirtpile", 150]],
  ["KINGPIN_DIRTPILE", ["Kingpin Dirtpile", 151]],
  ["D12_ROOM_FLOOR", ["D12 Room Floor", 880]],
  ["D12_ROOM_FLOOR_ACTIVATED", ["D12 Room Floor (Activated)", 881]],
  ["D12_PAL", ["D12 Pal", 0]],
  ["CHORISTER_AURA", ["Chorister Aura", 0]],
  ["GODS_MARBLE_EFFECT", ["God's Marble Effect", 0]],
  ["RANSACKED_WEB_CORPSE", ["Ransacked Web Corpse", 0]],
  ["FIEND_FLASH", ["Fiend Flash", 0]],
  ["FF_MULTIPURPOSE_EFFECT", ["FF Multipurpose Effect", 0]],
  ["DOUBLE_EFFECT", ["Double Effect", 0]],
  ["SPLASH", ["Splash", 0]],
  ["SPLASH", ["Splash", 0]],
  ["SPLASH", ["Splash", 1]],
  ["SPLASH", ["Splash", 0]],
  ["FIRE_GUNPOWDER", ["Fire (Gunpowder)", 0]],
  ["DOUBLE_EFFECT", ["Double Effect", 0]],
  ["DOUBLE_EFFECT_SMOKE", ["Double Effect Smoke", 0]],
  ["MELTY_POOF", ["Melty Poof", 0]],
  ["BLOODBEAM", ["Bloodbeam", 0]],
  ["PSYBEAM", ["Psybeam", 1]],
  ["SQUIRES_CLUB", ["Squire's Club", 0]],
  ["PSI_HUNTERS_CRUCIBLE", ["Psi Hunter's Crucible", 1]],
  ["EVIL_EXPLOSION", ["Evil Explosion", 0]],
  ["PSIONIC_CROSSHAIR", ["Psionic Crosshair", 0]],
  ["PSIONIC_CROSSHAIR", ["Psionic Crosshair", 1]],
  ["CURSE_CROSSHAIR", ["Curse Crosshair", 2]],
  ["RANCOR_CROSSHAIR", ["Rancor Crosshair", 3]],
  ["STINGER_PROJECTILE_POOF", ["Stinger Projectile Poof", 0]],
  ["HOMING_STINGER_PROJECTILE_POOF", ["Homing Stinger Projectile Poof", 1]],
  ["FIRE_FIEND", ["Fire (Fiend)", 0]],
  ["GLOBULON_BUBBLE", ["Globulon Bubble", 0]],
  ["PRIMEMIND_RETICLE", ["Primemind Reticle", 0]],
  ["DECORATIVE_EXPLOSION", ["Decorative Explosion", 0]],
  ["WATER_EXPLOSION", ["Water Explosion", 0]],
  ["SPORE_PROJECTILE_POOF", ["Spore Projectile Poof", 0]],
  ["WEAVER_HOLE", ["Weaver Hole", 0]],
  ["SOOTY_TEAR_POOF", ["Sooty Tear Poof", 0]],
  ["SOOTY_TEAR_2_POOF", ["Sooty Tear 2 Poof", 1]],
  ["FURNACE_BUBBLE", ["Furnace Bubble", 0]],
  ["MISTMONGER_APPARITION", ["Mistmonger Apparition", 0]],
  ["DOMINATOR_CHAIN", ["Dominator Chain", 0]],
  ["DENIED", ["Denied", 0]],
  ["MENACE_FLASH", ["Menace Flash", 0]],
  ["WARDEN_SPARKLE", ["Warden Sparkle", 0]],
  ["WARDEN_BARRIER", ["Warden Barrier", 0]],
  ["IMMURAL_CHAIN", ["Immural Chain", 0]],
  ["FISHAAC_CORPSE", ["Fishaac Corpse", 0]],
  ["DEEP_DWELLER_CORPSE", ["Deep Dweller Corpse", 1]],
  ["CORDIFY_MARKER", ["Cordify Marker", 0]],
  ["FUNNY_BLAST", ["FUNNY BLAST", 0]],
  ["GARYS_HOLE", ["Gary's Hole", 0]],
  ["CRITICAL_HIT", ["Critical Hit", 0]],
  ["FREAKY_BLOOD", ["Freaky Blood", 0]],
  ["TECHNOPINS_LASER", ["Technopin's Laser", 0]],
  ["CRIT_LIGHTNING", ["Crit Lightning", 1]],
  ["MEGA_HAEMOLACRIA_POOF", ["Mega Haemolacria Poof", 0]],
  ["HORSE_POOF", ["Horse Poof", 0]],
  ["GOB_NECK", ["Gob Neck", 0]],
  ["NUCLEAR_REVOLVER", ["Nuclear Revolver", 0]],
  ["D2", ["D2", 0]],
  ["D2", ["D2", 1]],
  ["DRIP_RETICLE", ["Drip Reticle", 0]],
  ["CRAWLSPACE_ROCKTOP", ["Crawlspace Rocktop", 0]],
  ["ONLOOKER_LASER", ["Onlooker Laser", 0]],
  ["SHI_CORPSE", ["Shi Corpse", 0]],
  ["CUFFS_CHAIN", ["Cuffs Chain", 0]],
  ["ROTSPIN_CHAIN", ["Rotspin Chain", 0]],
  ["FF_STATUS_ICON", ["FF Status Icon", 0]],
  ["SEWING_ROPE", ["Sewing Rope", 22]],
  ["SEWING_ROPE_MOVEMENT_HANDLER", ["Sewing Rope Movement Handler", 0]],
  ["SANGUINE_HOOK_ROPE", ["Sanguine Hook Rope", 24]],
  [
    "SANGUINE_HOOK_ROPE_MOVEMENT_HANDLER",
    ["Sanguine Hook Rope Movement Handler", 1],
  ],
  ["JOKE_PHONE_ROPE", ["Joke Phone Rope", 160]],
  [
    "JOKE_PHONE_ROPE_MOVEMENT_HANDLER",
    ["Joke Phone Rope Movement Handler", 160],
  ],
  ["INFINITY_VOLT_ROPE", ["Infinity Volt Rope", 161]],
  [
    "INFINITY_VOLT_ROPE_MOVEMENT_HANDLER",
    ["Infinity Volt Rope Movement Handler", 161],
  ],
  ["GRAPPLING_HOOK_ROPE", ["Grappling Hook Rope", 162]],
  [
    "GRAPPLING_HOOK_ROPE_MOVEMENT_HANDLER",
    ["Grappling Hook Rope Movement Handler", 162],
  ],
  ["SPAGHETTI_ROPE", ["Spaghetti Rope", 163]],
  ["SPAGHETTI_ROPE_MOVEMENT_HANDLER", ["Spaghetti Rope Movement Handler", 163]],
  ["TANGOS_AFTERIMAGE_", ["Tango's Afterimage (+)", 0]],
  ["TANGOS_AFTERIMAGE_X", ["Tango's Afterimage (x)", 1]],
  ["ANCHOR_AFTERIMAGE", ["Anchor Afterimage", 2]],
  ["MURASA_EFFECTS", ["Murasa Effects", 3]],
  ["PISS_DROPLETS", ["Piss Droplets", 4]],
  ["ROSE_QUARTZ_SHIELD", ["Rose Quartz Shield", 5]],
  ["SALT_LAMP_AURA", ["Salt Lamp Aura", 6]],
  ["FOCUS_CRYSTAL_RING", ["Focus Crystal Ring", 7]],
  ["FOCUS_CRYSTAL_POOF", ["Focus Crystal Poof", 8]],
  ["MAXS_FOSSIL_GHOST", ["Max's Fossil Ghost", 9]],
  ["CHAOS_CARD_LEFTOVER", ["Chaos Card Leftover", 10]],
  ["WARPZONE_PARTICLE", ["Warpzone Particle", 11]],
  ["KINETI_AURA", ["Kineti Aura", 114]],
  ["CHARMED_HEARTS", ["Charmed Hearts", 12]],
  ["ROSE_QUARTZ_SHIELD", ["Rose Quartz Shield", 13]],
  ["SHADOWLESS_ROCK_PROJECTILE", ["Shadowless Rock Projectile", 114]],
  ["SHADOWLESS_ROCK_SHADOW", ["Shadowless Rock Shadow", 14]],
  ["SHADOWLESS_GRID_PROJECTILE", ["Shadowless Grid Projectile", 114]],
  ["ASTROPULVIS_GHOST", ["Astropulvis Ghost", 15]],
  ["HOLY_WOBBLES_BEAM", ["Holy Wobbles Beam", 16]],
  ["LUNKSACK_NEEDLE", ["Lunksack Needle", 17]],
  ["CHORUS_AFTERIMAGE", ["Chorus' Afterimage", 18]],
  ["MOONBEAM_TARGET", ["Moonbeam Target", 19]],
  ["MOONBEAM_LIGHT", ["Moonbeam Light", 20]],
  ["WOMAN_INDICATOR", ["Woman Indicator", 21]],
  ["GAY_AFTERIMAGE", ["Gay Afterimage", 22]],
  ["GRIMACE_ROCK", ["Grimace Rock", 0]],
  ["VOMIT_GRIMACE_ROCK", ["Vomit Grimace Rock", 1]],
  ["WETSTONE_ROCK", ["Wetstone Rock", 2]],
  ["CONSTANT_STONE_SHOOTER_ROCK", ["Constant Stone Shooter Rock", 3]],
  ["BROKEN_GAPING_MAW_ROCK", ["Broken Gaping Maw Rock", 4]],
  ["BRIMSTONE_HEAD_ROCK", ["Brimstone Head Rock", 5]],
  ["CROSS_STONE_SHOOTER_ROCK", ["Cross Stone Shooter Rock", 6]],
  ["STONE_EYE_ROCK", ["Stone Eye Rock", 7]],
  ["CAULDRON_ROCK", ["Cauldron Rock", 8]],
  ["GAPING_MAW_ROCK", ["Gaping Maw Rock", 9]],
  ["TRIPLE_GRIMACE_ROCK", ["Triple Grimace Rock", 10]],
  ["SENSORY_GRIMACE_ROCK", ["Sensory Grimace Rock", 11]],
  ["GHOSTBUSTER_BLINK", ["Ghostbuster Blink", 0]],
  ["GHOSTBUSTER_SWIRL", ["Ghostbuster Swirl", 0]],
  ["GHOSTBUSTER_TARGET", ["Ghostbuster Target", 0]],
  ["CRAWLSPACE_GRID_RERENDERER", ["Crawlspace Grid Rerenderer", 0]],
  ["SLIPPERY_BLUE_CREEP", ["Slippery Blue Creep", 160]],
  ["BLOOD_JET", ["Blood Jet", 160]],
  ["DUMMY_ROPE_TARGET", ["Dummy Rope Target", 0]],
  ["GUT_CLOUD", ["Gut Cloud", 10]],
  ["LYRE_PARTICLE", ["Lyre Particle", 11]],
  ["FF_WHITE_SMOKE", ["FF White Smoke", 12]],
  ["PSYCHIC_RINGS", ["Psychic Rings", 13]],
  ["LOVE_HEART", ["Love Heart", 14]],
  ["SECRET_GHOST", ["Secret Ghost", 15]],
  ["FAIRY_WEAPON", ["Fairy Weapon", 16]],
  ["CHIRUMIRU_FLASH", ["Chirumiru Flash", 20]],
  ["MIME_BLOCK", ["Mime Block", 21]],
  ["RIDICULOUS_NOTE", ["Ridiculous Note", 22]],
  ["PIZZA_BOX", ["Pizza Box", 23]],
  ["MELTDOWN_FLASH", ["Meltdown Flash", 24]],
  ["FOG_OF_WAR", ["Fog of War", 30]],
  ["DUSKS_HANDS_AFTERIMAGE", ["Dusk's Hand's Afterimage", 31]],
  ["FAKE_DUSK", ["Fake Dusk", 32]],
  ["FAKE_BLOODPOOF", ["Fake Bloodpoof", 33]],
  ["DUSKS_ARM", ["Dusk's Arm", 34]],
  ["POKER_WAGER", ["Poker Wager", 40]],
  ["SMALL_CLUTCHS_TAIL", ["Small Clutch's Tail", 41]],
  ["KALUS_VISAGE", ["Kalu's Visage", 42]],
  ["NIL_PASTA_END", ["Nil Pasta End", 43]],
  ["NIL_PASTA_END", ["Nil Pasta End", 44]],
  ["GRAPPLING_HOOK", ["Grappling Hook", 50]],
  ["GRAPPLING_HOOK", ["Grappling Hook", 51]],
  ["LITTLE_GRAPPLING_HOOK", ["Little Grappling Hook", 52]],
  ["SWALLOWED_M90_GUN", ["Swallowed M90 Gun", 60]],
  ["GOLEMS_AR_GUN", ["Golem's AR Gun", 61]],
  ["GOLEMS_AR_BULLET_CASES", ["Golem's AR Bullet Cases", 62]],
  ["BIGSPLASH", ["BigSplash", 70]],
  ["DEAD_VERMIN", ["Dead Vermin", 71]],
  ["ONLYFAN_IMAGE", ["Onlyfan Image", 72]],
  ["FF_KNIFE_SWIPE", ["FF Knife Swipe", 80]],
  ["FF_KNIFE_SWIPE", ["FF Knife Swipe", 90]],
  ["TECHSHOT_POOF", ["Techshot Poof", 100]],
  ["LOOKSEE_HAND", ["Looksee Hand", 110]],
  ["OWL_STAR_MINOR", ["Owl Star (Minor)", 120]],
  ["BALL_OF_MALICE", ["Ball of Malice", 130]],
  ["BALL_OF_MINION", ["Ball of Minion", 131]],
  ["MALICE_MINION_GHOST", ["Malice Minion Ghost", 132]],
  ["ISAAC_SMONKING", ["Isaac Smonking", 140]],
  ["WHIRLPOOL", ["Whirlpool", 150]],
  ["AWESOME_POINTING_ARROW", ["Awesome Pointing Arrow", 160]],
  ["SOMETHING_THAT_FADES", ["Something that fades", 161]],
  ["DOGBOARD", ["Dogboard", 170]],
  ["LITTLE_PHONE", ["Little Phone", 180]],
  ["CAMERA_FLASH", ["Camera Flash", 190]],
  ["AXE_PROJECTILE", ["Axe Projectile", 200]],
  ["AXE_PROJECTILE_AFTER_IMAGE", ["Axe Projectile After image", 201]],
  ["TELEBOMBS_MARKER", ["Telebombs Marker", 210]],
  ["DEVIL_DAGGER_PROJECTILE", ["Devil Dagger Projectile", 220]],
  ["DEVIL_DAGGER_GEM", ["Devil Dagger Gem", 221]],
  ["NITRO_STATUS", ["Nitro Status", 230]],
  ["INFINITY_VOLT", ["Infinity Volt", 250]],
  ["ATLAS_BOULDER", ["Atlas' Boulder", 251]],
  ["SHAGGOTH_GLOW_RENDERER", ["Shaggoth Glow Renderer", 1]],
  ["EYE_OF_SHAGGOTH_MARKER", ["Eye of Shaggoth Marker", 0]],
  ["EVENT_TRIGGER__ENEMIES_GROUP_0", ["Event Trigger - Enemies (Group 0)", 0]],
  ["EVENT_TRIGGER__ENEMIES_GROUP_1", ["Event Trigger - Enemies (Group 1)", 1]],
  ["EVENT_TRIGGER__ENEMIES_GROUP_2", ["Event Trigger - Enemies (Group 2)", 2]],
  ["EVENT_TRIGGER__ENEMIES_GROUP_3", ["Event Trigger - Enemies (Group 3)", 3]],
  ["EVENT_TRIGGER__ENEMIES_ALL_0", ["Event Trigger - Enemies (All 0)", 10]],
  ["EVENT_TRIGGER__ENEMIES_ALL_1", ["Event Trigger - Enemies (All 1)", 11]],
  ["EVENT_TRIGGER__ENEMIES_ALL_2", ["Event Trigger - Enemies (All 2)", 12]],
  ["EVENT_TRIGGER__ENEMIES_ALL_3", ["Event Trigger - Enemies (All 3)", 13]],
  ["PULSE_EFFECT_SMALL", ["Pulse Effect (Small)", 150]],
  ["PULSE_EFFECT_BIG", ["Pulse Effect (Big)", 150]],
  ["BURIED_FOSSIL_PATCH", ["Buried Fossil Patch", 114]],
  ["BURIED_FOSSIL_GRAPHIC", ["Buried Fossil Graphic", 0]],
  ["DOG_DOO_GFX", ["Dog Doo GFX", 0]],
  ["GOLEM_SUBWAY_TEXT", ["Golem Subway Text", 0]],
  ["FACADE", ["Facade", 0]],
  ["FIEND_FOLIO_SHOPKEEPER", ["Fiend Folio Shopkeeper", 0]],
  ["ROLY_POLY", ["Roly Poly", 0]],
  ["SEPTIC_POLY", ["Septic Poly", 1]],
  ["ISOPOLY", ["Isopoly", 2]],
  ["NIMBUS", ["Nimbus", 0]],
  ["SEPTIC_NIMBUS", ["Septic Nimbus", 1]],
  ["CISTERN", ["Cistern", 0]],
  ["STERNUM", ["Sternum", 0]],
  ["SPLODUM", ["Splodum", 0]],
  ["REHEATED_CHARGER", ["Reheated Charger", 0]],
  ["PSYCHO_FLY", ["Psycho Fly", 0]],
  ["DOOM_FLY", ["Doom Fly", 0]],
  ["GOLDEN_BOOM_FLY", ["Golden Boom Fly", 0]],
  ["WARHEAD", ["Warhead", 0]],
  ["DRAINER", ["Drainer", 0]],
  ["REHEATED_HOST", ["Reheated Host", 710]],
  ["REHEATED_HOST", ["Reheated Host", 711]],
  ["REHEATED_HOST", ["Reheated Host", 712]],
  ["TOT", ["Tot", 0]],
  ["SPINNERETCH", ["Spinneretch", 0]],
  ["SOURPATCH_HEAD", ["Sourpatch Head", 0]],
  ["LIMEPATCH_HEAD", ["Limepatch Head", 1]],
  ["BOMBMUNCHER", ["Bombmuncher", 5]],
  ["STICKY_SACK", ["Sticky Sack", 0]],
  ["WALKING_STICKY_SACK", ["Walking Sticky Sack", 0]],
  ["STUMBLING_STICKY_SACK", ["Stumbling Sticky Sack", 0]],
  ["CREPITUS", ["Crepitus", 0]],
  ["MR_BONES", ["Mr. Bones", 0]],
  ["HOLLOW_KNIGHT", ["Hollow Knight", 0]],
  ["PSIONIC_KNIGHT", ["Psionic Knight", 0]],
  ["POWDERKEG", ["Powderkeg", 0]],
  ["WETSTONE", ["Wetstone", 0]],
  ["CAULDRON", ["Cauldron", 0]],
  ["FURNACE", ["Furnace", 0]],
  ["SENSORY_GRIMACE", ["Sensory Grimace", 0]],
  ["ARTERY_MOBILE", ["Artery (Mobile)", 0]],
  ["ARTERY_SPINNING", ["Artery (Spinning)", 0]],
  ["VEIN", ["Vein", 0]],
  ["SEPTIC_PIPE", ["Septic Pipe", 0]],
  ["SEWER_PIPE", ["Sewer Pipe", 0]],
  ["SLUDGE_PIPE", ["Sludge Pipe", 0]],
  ["SPHINCTER", ["Sphincter", 0]],
  ["SPLIT_PIPE", ["Split Pipe", 0]],
  ["GRATE", ["Grate", 0]],
  ["HUNGRY_PARABITE", ["Hungry Para-Bite", 0]],
  ["SPITROAST", ["Spitroast", 0]],
  ["SPITFIRE", ["Spitfire", 0]],
  ["SPOOTER", ["Spooter", 0]],
  ["SUPER_SPOOTER", ["Super Spooter", 0]],
  ["BABY_SPIDER", ["Baby Spider", 0]],
  ["MEGA_SPOOTER", ["Mega Spooter", 0]],
  ["LITTER_BUG", ["Litter Bug", 0]],
  ["TOXIC_LITTER_BUG", ["Toxic Litter Bug", 0]],
  ["CHARMED_LITTER_BUG", ["Charmed Litter Bug", 0]],
  ["GUTBUSTER", ["Gutbuster", 0]],
  ["KRASS_BLASTER", ["Krass Blaster", 0]],
  ["JAWBONE", ["Jawbone", 0]],
  ["SQUIDGE", ["Squidge", 0]],
  ["TUBBY", ["Tubby", 0]],
  ["MOUTHFUL", ["Mouthful", 0]],
  ["BIG_SMOKE", ["Big Smoke", 0]],
  ["BIGHEAD", ["Bighead", 0]],
  ["PSYCHIC_GAPER", ["Psychic Gaper", 0]],
  ["WALL_GAPER", ["Wall Gaper", 0]],
  ["ICKY_FLY", ["Icky Fly", 0]],
  ["BOBBY_FLY", ["Bobby Fly", 0]],
  ["REHEATED_FLY", ["Reheated Fly", 0]],
  ["SACKY_FLY", ["Sacky Fly", 0]],
  ["CHOMPY_FLY", ["Chompy Fly", 0]],
  ["TICKING_FLY", ["Ticking Fly", 0]],
  ["FULL_SPIDER", ["Full Spider", 0]],
  ["BOBBY_SPIDER", ["Bobby Spider", 0]],
  ["REHEATED_SPIDER", ["Reheated Spider", 0]],
  ["SACKY_SPIDER", ["Sacky Spider", 0]],
  ["ICKY_SPIDER", ["Icky Spider", 0]],
  ["CHOMPY_SPIDER", ["Chompy Spider", 0]],
  ["REHEATED_GURGLE", ["Reheated Gurgle", 0]],
  ["REHEATED_CYCLOPIA", ["Reheated Cyclopia", 0]],
  ["SPARK", ["Spark", 0]],
  ["FRIED", ["Fried", 0]],
  ["OGRE_CREEP", ["Ogre Creep", 0]],
  ["ICKY_CREEP", ["Icky Creep", 0]],
  ["TECHY_CREEP", ["Techy Creep", 0]],
  ["BONE_WORM", ["Bone Worm", 0]],
  ["BONER_WORM", ["Boner Worm", 10]],
  ["BUBBLE_BAT", ["Bubble Bat", 0]],
  ["RIBBONE", ["Ribbone", 0]],
  ["FUEGO", ["Fuego", 0]],
  ["DANGLER", ["Dangler", 0]],
  ["SOFT_SERVE", ["Soft Serve", 0]],
  ["SUNDAE", ["Sundae", 0]],
  ["SCOOP", ["Scoop", 0]],
  ["LOAD", ["Load", 0]],
  ["CORN_LOAD", ["Corn Load", 0]],
  ["BARO", ["Baro", 0]],
  ["CHORISTER", ["Chorister", 0]],
  ["FOAMY", ["Foamy", 0]],
  ["FATHEAD", ["Fathead", 0]],
  ["SKUZZ", ["Skuzz", 0]],
  ["RANSACKED", ["Ransacked", 0]],
  ["SKUZZBALL", ["Skuzzball", 0]],
  ["SKUZZBALL_SMALL", ["Skuzzball (Small)", 0]],
  ["BOILER", ["Boiler", 0]],
  ["DRINK_WORM", ["Drink Worm", 0]],
  ["DRUNK_WORM", ["Drunk Worm", 0]],
  ["WOBBLES", ["Wobbles", 0]],
  ["SLUDGE_HOST", ["Sludge Host", 0]],
  ["CREEPTERUM", ["Creepterum", 0]],
  ["CORPOSLAVE", ["Corposlave", 0]],
  ["CURDLE", ["Curdle", 0]],
  ["CURDLE_NAKED", ["Curdle (Naked)", 0]],
  ["CALZONE", ["Calzone", 0]],
  ["PANINI", ["Panini", 1]],
  ["BREADBIN", ["Breadbin", 0]],
  ["HONEYDROP", ["Honeydrop", 0]],
  ["BELLA", ["Bella", 0]],
  ["MARGE", ["Marge", 0]],
  ["HEIRESS", ["Heiress", 0]],
  ["HEIRESS_SKULL", ["Heiress Skull", 0]],
  ["QUEENY_III", ["Queeny III", 0]],
  ["PATZER", ["Patzer", 0]],
  ["PATZER_SHELL", ["Patzer Shell", 0]],
  ["DOPES_HEAD", ["Dope's Head", 0]],
  ["HONEY_EYE", ["Honey Eye", 0]],
  ["SMOGGER", ["Smogger", 0]],
  ["TEMPER", ["Temper", 0]],
  ["SPINNY", ["Spinny", 0]],
  ["DIZZY", ["Dizzy", 0]],
  ["CONGRESSION", ["Congression", 0]],
  ["CONGRESSION_W", ["Congression W", 0]],
  ["LIGHTNING_FLY", ["Lightning Fly", 0]],
  ["BLOT", ["Blot", 0]],
  ["MELTY", ["Melty", 0]],
  ["PITCHER", ["Pitcher", 0]],
  ["MUTANT_HORF", ["Mutant Horf", 0]],
  ["PHOENIX", ["Phoenix", 0]],
  ["PHOENIX_CORPSE", ["Phoenix (Corpse)", 1]],
  ["PHOENIX_REVIVED", ["Phoenix (Revived)", 2]],
  ["PYROCLASM", ["Pyroclasm", 0]],
  ["PRICK", ["Prick", 0]],
  ["BLASTCORE", ["Blastcore", 0]],
  ["SKIPPER", ["Skipper", 0]],
  ["GOBHOPPER", ["Gobhopper", 170]],
  ["CUSHION", ["Cushion", 0]],
  ["SLAMMER", ["Slammer", 0]],
  ["WIMPY", ["Wimpy", 0]],
  ["STONEY_SLAMMER", ["Stoney Slammer", 0]],
  ["CRAZY_STONEY_SLAMMER", ["Crazy Stoney Slammer", 0]],
  ["SMASHER", ["Smasher", 0]],
  ["SMORE", ["S'More", 0]],
  ["SEPTIC", ["S'Eptic", 0]],
  ["STOMPY", ["Stompy", 0]],
  ["DOOMER", ["Doomer", 0]],
  ["MARZLAMMER", ["Marzlammer", 0]],
  ["FLINTY", ["Flinty", 0]],
  ["SQUARE_FLY", ["Square Fly", 0]],
  ["SNIFFLE", ["Sniffle", 0]],
  ["DRY_WHEEZE", ["Dry Wheeze", 0]],
  ["SNAGGER", ["Snagger", 0]],
  ["WEAVER", ["Weaver", 0]],
  ["WEAVER_SR", ["Weaver Sr.", 0]],
  ["DREAD_WEAVER", ["Dread Weaver", 0]],
  ["THREAD", ["Thread", 0]],
  ["ARCHER", ["Archer", 0]],
  ["DIAGETIC", ["Diagetic", 0]],
  ["CRATERFACE", ["Craterface", 0]],
  ["DROOLER", ["Drooler", 0]],
  ["BLAZER", ["Blazer", 0]],
  ["PSION", ["Psion", 0]],
  ["POOPLE", ["Poople", 0]],
  ["DUNG", ["Dung", 0]],
  ["MEATWAD", ["Meatwad", 0]],
  ["SLAG", ["Slag", 0]],
  ["POX", ["Pox", 0]],
  ["HAUNCH", ["Haunch", 0]],
  ["OUTLIER", ["Outlier", 0]],
  ["GRILLED_MEATWAD", ["Grilled Meatwad", 0]],
  ["OFFAL", ["Offal", 0]],
  ["DRIED_OFFAL", ["Dried Offal", 0]],
  ["MORSEL", ["Morsel", 0]],
  ["FALAFEL", ["Falafel", 0]],
  ["CANCERLET", ["Cancerlet", 1]],
  ["SLICK", ["Slick", 0]],
  ["STUMP", ["Stump", 0]],
  ["FROG", ["Frog", 0]],
  ["MOTOR_NEURON", ["Motor Neuron", 0]],
  ["DWELLER", ["Dweller", 0]],
  ["DWELLER_INNER_EYE", ["Dweller (Inner Eye)", 2]],
  ["DWELLER_SPOON_BENDER", ["Dweller (Spoon Bender)", 3]],
  ["DWELLER_NUMBER_ONE", ["Dweller (Number One)", 6]],
  ["DWELLER_BROTHER_BOBBY", ["Dweller (Brother Bobby)", 8]],
  ["DWELLER_TECHNOLOGY", ["Dweller (Technology)", 68]],
  ["DWELLER_POLYPHEMUS", ["Dweller (Polyphemus)", 169]],
  ["DWELLER_LOST_CONTACT", ["Dweller (Lost Contact)", 213]],
  ["DWELLER_CRICKETS_BODY", ["Dweller (Cricket's Body)", 224]],
  ["DWELLER_CURSED_EYE", ["Dweller (Cursed Eye)", 316]],
  ["DWELLER_SOY_MILK", ["Dweller (Soy Milk)", 330]],
  ["DWELLER_EUTHANASIA", ["Dweller (Euthanasia)", 496]],
  ["DWELLER_RANDOM", ["Dweller (Random)", 1000]],
  ["DWELLER_BROTHER", ["Dweller Brother", 0]],
  ["RESIDENT", ["Resident", 0]],
  ["RESIDENT_BODY", ["Resident Body", 0]],
  ["MISSING_LINK", ["Missing Link", 0]],
  ["MISSING_LINK_HARLEQUIN_BABY", ["Missing Link (Harlequin Baby)", 167]],
  [
    "MISSING_LINK_THE_LUDOVICO_TECHNIQUE",
    ["Missing Link (The Ludovico Technique)", 329],
  ],
  ["MISSING_LINK_GODHEAD", ["Missing Link (Godhead)", 331]],
  ["MISSING_LINK_CONTINUUM", ["Missing Link (Continuum)", 369]],
  ["MISSING_LINK_TECH_X", ["Missing Link (Tech X)", 395]],
  ["MISSING_LINK_VARICOSE_VEINS", ["Missing Link (Varicose Veins)", 452]],
  ["MISSING_LINK_RANDOM", ["Missing Link (Random)", 1000]],
  ["HARLEY", ["Harley", 0]],
  ["WARTY", ["Warty", 0]],
  ["GUNK", ["Gunk", 0]],
  ["PUNK", ["Punk", 0]],
  ["GLEEK", ["Gleek", 0]],
  ["RIBEYE", ["Ribeye", 0]],
  ["CORTEX", ["Cortex", 0]],
  ["GORGER", ["Gorger", 0]],
  ["DROP", ["Drop", 0]],
  ["DRIBBLE", ["Dribble", 0]],
  ["GLOB", ["Glob", 0]],
  ["SIZZLE", ["Sizzle", 0]],
  ["FOSSIL", ["Fossil", 0]],
  ["SENTRY", ["Sentry", 0]],
  ["SENTRY_SHELL", ["Sentry Shell", 1]],
  ["MOLD", ["Mold", 0]],
  ["BALOR", ["Balor", 0]],
  ["SEPTIC_BALOR", ["Septic Balor", 1]],
  ["EYESORE", ["Eyesore", 0]],
  ["GANDER", ["Gander", 0]],
  ["BEETER", ["Beeter", 0]],
  ["LIL_JON", ["Lil' Jon", 0]],
  ["ELITE_JON", ["Elite Jon", 1]],
  ["CROSSEYES", ["Crosseyes", 0]],
  ["TADO_KID", ["Tado Kid", 0]],
  ["TOXIC_KNIGHT", ["Toxic Knight", 0]],
  ["HAUNTED", ["Haunted", 0]],
  ["YAWNER", ["Yawner", 0]],
  ["FISHFACE", ["Fishface", 0]],
  ["FISHFACE_WAITING", ["Fishface (Waiting)", 1]],
  ["SHINY_FISHFACE", ["Shiny Fishface", 0]],
  ["BUBBLE_BLOWING_DOUBLE_BABY", ["Bubble Blowing Double Baby", 0]],
  ["SPITUM", ["Spitum", 0]],
  ["GHOSTSE", ["Ghostse", 0]],
  ["GHOSTSE_EASY_MODE", ["Ghostse (Easy Mode)", 0]],
  ["SEPTIC_GHOSTSE", ["Septic Ghostse", 0]],
  ["MR_FLARE", ["Mr. Flare", 0]],
  ["MR_CRISPLY", ["Mr. Crisply", 0]],
  ["INCISOR", ["Incisor", 0]],
  ["STARVING", ["Starving", 0]],
  ["WOODBURNER", ["Woodburner", 0]],
  ["WOODBURNER_EASY_MODE", ["Woodburner (Easy mode)", 0]],
  ["MILK_TOOTH", ["Milk Tooth", 0]],
  ["SQUIRE", ["Squire", 0]],
  ["FORESEER", ["Foreseer", 0]],
  ["PSLEECH", ["Psleech", 0]],
  ["FUMEGEIST", ["Fumegeist", 0]],
  ["MOTE", ["Mote", 0]],
  ["SOURPATCH", ["Sourpatch", 0]],
  ["SOURPATCH_BODY", ["Sourpatch Body", 0]],
  ["LIMEPATCH", ["Limepatch", 1]],
  ["LIMEPATCH_BODY", ["Limepatch Body", 1]],
  ["MOBILE_BLOOD_CELL", ["Mobile Blood Cell", 0]],
  ["SPINNING_BLOOD_CELL", ["Spinning Blood Cell", 0]],
  ["MADCLAW", ["Madclaw", 0]],
  ["HEAD_HONCHO", ["Head Honcho", 0]],
  ["COLONEL", ["Colonel", 0]],
  ["RETIRED_COLONEL", ["Retired Colonel", 200]],
  ["ZINGLING", ["Zingling", 0]],
  ["ZINGY", ["Zingy", 0]],
  ["GLOBULON", ["Globulon", 0]],
  ["PRIMEMIND", ["Primemind", 0]],
  ["CHARLIE", ["Charlie", 0]],
  ["SOOTY", ["Sooty", 0]],
  ["ULTIMATE_SMOKIN", ["Ultimate Smokin", 0]],
  ["SMOKIN", ["Smokin", 0]],
  ["FLAMIN", ["Flamin", 0]],
  ["FLAMIN_CHAIN", ["Flamin Chain", 0]],
  ["FLICKERSPIRIT", ["Flickerspirit", 0]],
  ["ETERNAL_FLICKERSPIRIT", ["Eternal Flickerspirit", 0]],
  ["DEADFLY", ["Deadfly", 0]],
  ["ETERNAL_FLY", ["Eternal Fly", 0]],
  ["DOGMEAT", ["Dogmeat", 0]],
  ["BROOTER", ["Brooter", 0]],
  ["TAP", ["Tap", 0]],
  ["TALL_BOI", ["Tall Boi", 0]],
  ["SHITLING", ["Shitling", 0]],
  ["REALLY_TALL_BOI", ["Really Tall Boi", 0]],
  ["PEEPLING", ["Peepling", 0]],
  ["HARLETWIN", ["Harletwin", 0]],
  ["HARLETWIN_CORD", ["Harletwin Cord", 1]],
  ["EFFIGY", ["Effigy", 0]],
  ["EFFIGY_CORD", ["Effigy Cord", 1]],
  ["GIS", ["Gis", 0]],
  ["CENTIPEDE", ["Centipede", 0]],
  ["CENTIPEDE_SEGMENT", ["Centipede Segment", 1]],
  ["ANGY_CENTIPEDE", ["Angy Centipede", 0]],
  ["MULLIKABOOM", ["Mullikaboom", 0]],
  ["POOBOTTLE", ["Poobottle", 0]],
  ["DRAINFLY", ["Drainfly", 0]],
  ["GRATER", ["Grater", 0]],
  ["TOMBIT", ["Tombit", 0]],
  ["GRAVIN", ["Gravin", 0]],
  ["HOMER", ["Homer", 0]],
  ["GISHLE", ["Gishle", 0]],
  ["HOVER", ["Hover", 0]],
  ["SAGGING_SUCKER", ["Sagging Sucker", 0]],
  ["SAGGING_SPIT", ["Sagging Spit", 0]],
  ["RED_HORF", ["Red Horf", 0]],
  ["SHITTY_HORF", ["Shitty Horf", 0]],
  ["ZAPBLADDER", ["Zapbladder", 0]],
  ["WIRE", ["Wire", 0]],
  ["PIPER", ["Piper", 0]],
  ["SCYTHE_RIDER", ["Scythe Rider", 0]],
  ["PITCHFORK_HITCHER", ["Pitchfork Hitcher", 0]],
  ["REAPER", ["Reaper", 0]],
  ["MS_DOMINATOR", ["Ms. Dominator", 0]],
  ["DOMINATED", ["Dominated", 0]],
  ["FOSSILIZED_BOOM_FLY", ["Fossilized Boom Fly", 0]],
  ["STINGLER", ["Stingler", 0]],
  ["TRICKLE_FLYING", ["Trickle (Flying)", 0]],
  ["TRICKLE_SKITTERING", ["Trickle (Skittering)", 1]],
  ["BUNCH", ["Bunch", 0]],
  ["GRAPE", ["Grape", 1]],
  ["FISHAAC", ["Fishaac", 0]],
  ["BUMBLER", ["Bumbler", 0]],
  ["BUCKSHOT", ["Buckshot", 0]],
  ["MENACE", ["Menace", 0]],
  ["THOUSAND_EYES", ["Thousand Eyes", 0]],
  ["WARDEN", ["Warden", 0]],
  ["ERODED_HOST", ["Eroded Host", 0]],
  ["IMMURAL", ["Immural", 0]],
  ["SHIITAKE", ["Shiitake", 0]],
  ["BOWLER", ["Bowler", 0]],
  ["LOAFER", ["Loafer", 1]],
  ["BOWLER_BALL", ["Bowler Ball", 2]],
  ["STRIKER", ["Striker", 0]],
  ["PALE_LOAFER", ["Pale Loafer", 1]],
  ["STRIKER_BALL", ["Striker Ball", 2]],
  ["SEPTIC_BOWLER", ["Septic Bowler", 0]],
  ["SEPTIC_LOAFER", ["Septic Loafer", 1]],
  ["SEPTIC_BOWLER_BALL", ["Septic Bowler Ball", 2]],
  ["MR_HORF", ["Mr. Horf", 0]],
  ["THROWN_HORF", ["Thrown Horf", 0]],
  ["MR_RED_HORF", ["Mr. Red Horf", 0]],
  ["THROWN_RED_HORF", ["Thrown Red Horf", 0]],
  ["MR_GURGLE", ["Mr. Gurgle", 0]],
  ["THROWN_GURGLE_HEAD", ["Thrown Gurgle Head", 0]],
  ["MR_SUB_HORF", ["Mr. Sub Horf", 0]],
  ["CORDIFY", ["Cordify", 0]],
  ["SPOOK", ["Spook", 0]],
  ["UTERO_PILLAR", ["Utero Pillar", 0]],
  ["ORGANELLE", ["Organelle", 0]],
  ["HONEYDRIP", ["Honeydrip", 0]],
  ["SLIM", ["Slim", 0]],
  ["LIMB", ["Limb", 2]],
  ["PALE_SLIM", ["Pale Slim", 0]],
  ["JIM", ["Jim", 1]],
  ["PALE_LIMB", ["Pale Limb", 2]],
  ["SLIM_SHADY", ["Slim Shady", 0]],
  ["RED_HAND", ["Red Hand", 2]],
  ["PESTER", ["Pester", 0]],
  ["RAMBLIN_EVIL_MUSHROOM", ["Ramblin' Evil Mushroom", 0]],
  ["BOLA", ["Bola", 0]],
  ["BOLA_NECK", ["Bola Neck", 2]],
  ["SMIDGEN", ["Smidgen", 0]],
  ["RED_SMIDGEN", ["Red Smidgen", 0]],
  ["ERODED_SMIDGEN", ["Eroded Smidgen", 0]],
  ["TITTLE", ["Tittle", 0]],
  ["ARMOURED_LOOKER", ["Armoured Looker", 0]],
  ["LOOKER", ["Looker", 1]],
  ["PEEKABOO", ["Peek-a-boo", 0]],
  ["PEEKABOO_EYE", ["Peek-a-boo Eye", 0]],
  ["RING_OF_RING_FLIES", ["Ring of Ring Flies", 0]],
  ["DR_SHAMBLES", ["Dr. Shambles", 0]],
  ["INNER_EYE", ["Inner Eye", 0]],
  ["ENLIGHTENED", ["Enlightened", 0]],
  ["UNENLIGHTENED", ["Unenlightened", 1]],
  ["MR_GOB", ["Mr. Gob", 0]],
  ["GOB", ["Gob", 0]],
  ["GLOBSCRAPER", ["Globscraper", 0]],
  ["FOE", ["Foe", 0]],
  ["PSI_HUNTER", ["Psi Hunter", 0]],
  ["HELPER_HUNTER", ["Helper Hunter", 10]],
  ["PSILING", ["Psiling", 0]],
  ["UMBRA", ["Umbra", 0]],
  ["BLISTERED_UMBRA", ["Blistered Umbra", 1]],
  ["ECLIPSE", ["Eclipse", 0]],
  ["SEEKER", ["Seeker", 0]],
  ["C_WORD", ["C Word", 0]],
  ["NEONATE", ["Neonate", 0]],
  ["FLANKS", ["Flanks", 0]],
  ["CARRIER", ["Carrier", 0]],
  ["QUACK", ["Quack", 0]],
  ["LIPOMA", ["Lipoma", 0]],
  ["NANNY_LONG_LEGS", ["Nanny Long Legs", 0]],
  ["COBY", ["Coby", 0]],
  ["ROOK", ["Rook", 0]],
  ["FINGORE", ["Fingore", 0]],
  ["POINTING_FINGORE", ["Pointing Fingore", 1]],
  ["FINGORES_SCRUPULATOR", ["Fingore's Scrupulator", 0]],
  ["MINIMIN", ["Mini-Min", 0]],
  ["GUTTER", ["Gutter", 0]],
  ["SIXTH", ["Sixth", 0]],
  ["RESIDUUM", ["Residuum", 0]],
  ["TECHNICIAN", ["Technician", 0]],
  ["LOOKSEE", ["Looksee", 0]],
  ["CLERGY", ["Clergy", 0]],
  ["STOLAS", ["Stolas", 0]],
  ["DEATHANY", ["Deathany", 0]],
  ["BULL", ["Bull", 0]],
  ["GEYSER", ["Geyser", 0]],
  ["SUPER_GRIMACE", ["Super Grimace", 0]],
  ["MAGNIFIER", ["Magnifier", 0]],
  ["MAG_GAPER", ["Mag Gaper", 0]],
  ["MEDIUM_GAPER", ["Medium Gaper", 100]],
  ["PALE_GAPER", ["Pale Gaper", 0]],
  ["APER", ["Aper", 0]],
  ["MATTE", ["Matte", 0]],
  ["BUNKER_WORM", ["Bunker Worm", 0]],
  ["BUCKETHEAD", ["Buckethead", 0]],
  ["BUBBY", ["Bubby", 0]],
  ["DISCY", ["Discy", 0]],
  ["NOBODY", ["Nobody", 1]],
  ["BEEBEE", ["Beebee", 0]],
  ["DELINQUENT", ["Delinquent", 0]],
  ["GRINNER", ["Grinner", 0]],
  ["MOBILE_MUSHROOM", ["Mobile Mushroom", 0]],
  ["ONLYFAN", ["Onlyfan", 0]],
  ["DESIRER", ["Desirer", 0]],
  ["WANING_DESIRER", ["Waning Desirer", 0]],
  ["DIMINISHED_DESIRER", ["Diminished Desirer", 0]],
  ["SEDUCER", ["Seducer", 0]],
  ["BUOY", ["Buoy", 0]],
  ["PALE_HORF", ["Pale Horf", 0]],
  ["MAG_HORF", ["Mag Horf", 0]],
  ["PALE_CLOTTY", ["Pale Clotty", 0]],
  ["MAG_CLOTTY", ["Mag Clotty", 0]],
  ["HOLY_CLOTTY", ["Holy Clotty", 0]],
  ["SLOBBER", ["Slobber", 0]],
  ["BLEEDER", ["Bleeder", 0]],
  ["PALE_BLEEDER", ["Pale Bleeder", 0]],
  ["ICE_HAZARD_MORSELS", ["Ice Hazard Morsels", 0]],
  ["ICE_HAZARD_SLAMMER", ["Ice Hazard Slammer", 0]],
  ["VOLT", ["Volt", 0]],
  ["PEPPER_STATUE_ISAAC", ["Pepper Statue (Isaac)", 0]],
  ["PEPPER_STATUE_MAGGY", ["Pepper Statue (Maggy)", 1]],
  ["PEPPER_STATUE_FIEND", ["Pepper Statue (Fiend)", 2]],
  ["VALVO", ["Valvo", 0]],
  ["SOMBRA", ["Sombra", 0]],
  ["WOMB_PILLAR", ["Womb Pillar", 0]],
  ["WATCHER", ["Watcher", 0]],
  ["WATCHER_EYE", ["Watcher Eye", 0]],
  ["MISTMONGER", ["Mistmonger", 0]],
  ["CORDEND", ["Cordend", 0]],
  ["CORDENDS_RIGHT_HALF", ["Cordend's Right Half", 1]],
  ["CORDEND_CORD", ["Cordend Cord", 2]],
  ["GUFLUSH", ["Guflush", 0]],
  ["RANCOR", ["Rancor", 0]],
  ["CANCER_BOY", ["Cancer Boy", 0]],
  ["EYE_OF_SHAGGOTH", ["Eye of Shaggoth", 0]],
  ["GRID_RESTOCK_MACHINE", ["Grid Restock Machine", 0]],
  ["PUNISHER", ["Punisher", 0]],
  ["BENIGN", ["Benign", 0]],
  ["DEWDROP", ["Dewdrop", 0]],
  ["CONNIPSHIT", ["Connipshit", 0]],
  ["TANGO", ["Tango", 0]],
  ["BELLOW", ["Bellow", 0]],
  ["FLOODFACE_RANDOM", ["Floodface (Random)", 0]],
  ["FLOODFACE_CHASING", ["Floodface (Chasing)", 1]],
  ["FROWNY", ["Frowny", 0]],
  ["PSYSTALK", ["Psystalk", 0]],
  ["CRUCIBLE", ["Crucible", 0]],
  ["CRUCIBLE_IGNITED", ["Crucible (Ignited)", 1]],
  ["FOUNT", ["Fount", 0]],
  ["DRILLBIT", ["Drillbit", 0]],
  ["MINIMOON", ["Minimoon", 0]],
  ["BLADDER", ["Bladder", 0]],
  ["HEARTBEAT", ["Heartbeat", 0]],
  ["IGNIS", ["Ignis", 0]],
  ["GLOBLET", ["Globlet", 0]],
  ["CROTCHETY", ["Crotchety", 0]],
  ["GABBER", ["Gabber", 0]],
  ["STALAGNAUGHT", ["Stalagnaught", 0]],
  ["ANTI_GOLEM", ["Anti Golem", 0]],
  ["TORMENT", ["Torment", 0]],
  ["ZISSURU", ["Zissuru", 0]],
  ["WHEEZER", ["Wheezer", 0]],
  ["GRITTY", ["Gritty", 0]],
  ["PSYCLOPIA", ["Psyclopia", 0]],
  ["PEEPISSER", ["Peepisser", 0]],
  ["BROOD", ["Brood", 0]],
  ["ALDERMAN", ["Alderman", 0]],
  ["UNSHORNZ", ["Unshornz", 0]],
  ["DREAD_MAW", ["Dread Maw", 0]],
  ["SPECTURN", ["Specturn", 0]],
  ["QUAKER", ["Quaker", 0]],
  ["SHAKER", ["Shaker", 0]],
  ["BRISKET", ["Brisket", 0]],
  ["ACCURSED", ["Accursed", 0]],
  ["MURMUR", ["Murmur", 0]],
  ["SHELLMET", ["Shellmet", 0]],
  ["NEMATODE", ["Nematode", 0]],
  ["G_HOST", ["G. Host", 0]],
  ["G_HOST_SPIRIT", ["G. Host Spirit", 1]],
  ["HOSTER", ["Hoster", 0]],
  ["CHUMMER", ["Chummer", 0]],
  ["HANGMAN", ["Hangman", 0]],
  ["SLIMER", ["Slimer", 0]],
  ["FRACTURE", ["Fracture", 0]],
  ["ARMY_SKUZZ", ["Army Skuzz", 0]],
  ["RING_SKUZZ", ["Ring Skuzz", 0]],
  ["FLAILER", ["Flailer", 0]],
  ["FLAILER_HEAD", ["Flailer Head", 1]],
  ["MITE", ["Mite", 0]],
  ["HOLY_WOBBLES", ["Holy Wobbles", 0]],
  ["FIRESWIRL", ["Fireswirl", 0]],
  ["WHALE", ["Whale", 0]],
  ["WHALE_GUTS", ["Whale Guts", 1]],
  ["WHALE_CORD", ["Whale Cord", 114]],
  ["CLAM", ["Clam", 0]],
  ["LUNKSACK", ["Lunksack", 0]],
  ["COLOSCOPE", ["Coloscope", 0]],
  ["PUTREFATTY", ["Putrefatty", 0]],
  ["MUSK", ["Musk", 0]],
  ["SPANKY", ["Spanky", 0]],
  ["SPIROLL", ["Spiroll", 0]],
  ["THWAMMY", ["Thwammy", 0]],
  ["ACOLYTE", ["Acolyte", 0]],
  ["EDEMA", ["Edema", 0]],
  ["REDEMA", ["Redema", 0]],
  ["FORGOTTEN_FETUS", ["Forgotten Fetus", 0]],
  ["LIL_AL", ["Lil Al", 0]],
  ["FORGOTTEN_FETUS_CORD", ["Forgotten Fetus Cord", 115]],
  ["FORGOTTEN_FETUS_HITBOX", ["Forgotten Fetus Hitbox", 10]],
  ["ANODE", ["Anode", 0]],
  ["ANODE_BEAM", ["Anode Beam", 115]],
  ["CHORUS", ["Chorus", 0]],
  ["LAIDERONNETTE", ["Laideronnette", 0]],
  ["CUBERT", ["Cubert", 0]],
  ["SCOWL_CREEP", ["Scowl Creep", 0]],
  ["CELLULITIS", ["Cellulitis", 0]],
  ["FLOATY", ["Floaty", 114]],
  ["PSYCHOKNIGHT", ["Psychoknight", 0]],
  ["SEA_CUCUMBER", ["Sea Cucumber", 0]],
  ["SCOPE_CREEP", ["Scope Creep", 0]],
  ["GRIEVANCE", ["Grievance", 0]],
  ["CASTED", ["Casted", 0]],
  ["ALFIL", ["Alfil", 0]],
  ["SHINE_SPIT", ["Shine Spit", 0]],
  ["MOUSE", ["Mouse", 0]],
  ["MINAMITSU_MURASA", ["Minamitsu Murasa", 0]],
  ["MURASAS_ANCHOR", ["Murasa's Anchor", 0]],
  [
    "HOLD_RELEASE_RAKSHASA_AND_CARCASSES",
    ["Hold, Release; Rakshasa and Carcasses", 0],
  ],
  ["FERRWAITING", ["FerrWaiting", 0]],
  ["BUCKET_PROJECTILE", ["Bucket Projectile", 0]],
  ["CUSTOM_MOTER", ["Custom Moter", 0]],
  ["CHUMMER_PATHFINDER", ["Chummer Pathfinder", 0]],
  ["SHADY_HOST", ["Shady Host", 0]],
  ["MAW_MR_BODY", ["Maw Mr. Body", 1]],
  ["MAW_MR", ["Maw Mr.", 0]],
  ["MR_PSYCHIC_MAW", ["Mr. Psychic Maw", 0]],
  ["MR_PSYCHIC_MAW_HEAD", ["Mr. Psychic Maw Head", 1]],
  ["PSYCHIC_GUSHER", ["Psychic Gusher", 2]],
  ["CHERRY_BOMB", ["Cherry Bomb", 0]],
  ["MOTHER_ORB", ["Mother Orb", 0]],
  ["JACKSON", ["Jackson", 0]],
  ["THE_FREEZER", ["The Freezer", 0]],
  ["PEAT", ["Peat", 0]],
  ["HORSE_CLASSIC", ["Horse (classic)", 0]],
  ["HORSE", ["Horse", 0]],
  ["COKEDUP_HORSE", ["Coked-up Horse", 1]],
  ["DEAD_HORSE", ["Dead Horse", 2]],
  ["DARK_HORSE", ["Dark Horse", 3]],
  ["CURSED_HORSE", ["Cursed Horse", 4]],
  ["HOLY_HORSE", ["Holy Horse", 5]],
  ["FORGOTTEN_HORSE", ["Forgotten Horse", 6]],
  ["SOUR_HORSE", ["Sour Horse", 7]],
  ["DROWNED_HORSE", ["Drowned Horse", 8]],
  ["FOETAL_HORSE", ["Foetal Horse", 9]],
  ["ASHEN_HORSE", ["Ashen Horse", 10]],
  ["STITCHED_HORSE", ["Stitched Horse", 11]],
  ["MINER_HORSE", ["Miner Horse", 12]],
  ["SPIDER_HORSE", ["Spider Horse", 13]],
  ["DANK_HORSE", ["Dank Horse", 14]],
  ["SECRET_HORSE", ["Secret Horse", 100]],
  ["GOLDEN_HORSE", ["Golden Horse", 101]],
  ["MISSING_HORSE", ["Missing Horse", 102]],
  ["FALSE_HORSE", ["False Horse", 103]],
  ["MINECRAFT_HORSE", ["Minecraft Horse", 104]],
  ["PONY", ["Pony", 0]],
  ["COKEDUP_PONY", ["Coked-up Pony", 1]],
  ["DEAD_PONY", ["Dead Pony", 2]],
  ["DARK_PONY", ["Dark Pony", 3]],
  ["CURSED_PONY", ["Cursed Pony", 4]],
  ["HOLY_PONY", ["Holy Pony", 5]],
  ["FORGOTTEN_PONY", ["Forgotten Pony", 6]],
  ["SOUR_PONY", ["Sour Pony", 7]],
  ["DROWNED_PONY", ["Drowned Pony", 8]],
  ["FOETAL_PONY", ["Foetal Pony", 9]],
  ["ASHEN_PONY", ["Ashen Pony", 10]],
  ["STITCHED_PONY", ["Stitched Pony", 11]],
  ["MINER_PONY", ["Miner Pony", 12]],
  ["SPIDER_PONY", ["Spider Pony", 13]],
  ["DANK_PONY", ["Dank Pony", 14]],
  ["TAINTED_HORSE", ["Tainted Horse", 0]],
  ["BABA", ["Baba", 0]],
  ["FISH_FROM_NUCLEAR_THRONE", ["Fish from Nuclear Throne", 0]],
  ["CRUDEMATE", ["Crudemate", 0]],
  ["BESERKER", ["Beserker", 0]],
  ["THE_BINDING_OF_ISAAC_REHEATED", ["The Binding of Isaac: Reheated", 0]],
  ["SPIDER_NICALIS", ["Spider (Nicalis)", 0]],
  ["CARROT", ["Carrot", 0]],
  ["MASTER_ATOM", ["Master Atom", 0]],
  ["SPLATTERCAP", ["Splattercap", 0]],
  ["CORDY", ["Cordy", 0]],
  ["BERRY", ["Berry", 0]],
  ["SPICY_DIP", ["Spicy Dip", 0]],
  ["POSSESSED", ["Possessed", 0]],
  ["POSSESSED_CORPSE", ["Possessed Corpse", 0]],
  ["MOANER", ["Moaner", 0]],
  ["UNPAWTUNATE", ["Unpawtunate", 0]],
  ["UNPAWTUNATE_SKULL", ["Unpawtunate Skull", 0]],
  ["MAMA_POOTER", ["Mama Pooter", 0]],
  ["CREEPY_MAGGOT", ["Creepy Maggot", 0]],
  ["GRAVEDIGGER", ["Gravedigger", 0]],
  ["GRAVEFIRE", ["Gravefire", 0]],
  ["SACKBOY", ["Sackboy", 0]],
  ["GNAWFUL", ["Gnawful", 0]],
  ["RAGURGE", ["Ragurge", 0]],
  ["WICK", ["Wick", 0]],
  ["BANSHEE", ["Banshee", 0]],
  ["FF_GRID_SPAWNER", ["FF Grid Spawner", 0]],
  ["FF_POOP_SPAWNER", ["FF Poop Spawner", 0]],
  ["FF_CUSTOM_CARD_SPAWNER", ["FF Custom Card Spawner", 0]],
  ["GLASS_DICE_SPAWNER", ["Glass Dice Spawner", 0]],
  ["CRACKER", ["Cracker", 0]],
  ["NUCHAL", ["Nuchal", 0]],
  ["NUCHAL_DETACHED", ["Nuchal (Detached)", 0]],
  ["NUCHAL_CORD", ["Nuchal (Cord)", 0]],
  ["OSSULARRY", ["Ossularry", 0]],
  ["ROTSPIN", ["Rotspin", 0]],
  ["ROTSPIN_MOON", ["Rotspin Moon", 0]],
  ["SPOILIE", ["Spoilie", 0]],
  ["CLICKETY_CLASH", ["Clickety Clash", 0]],
  ["CONGLOBBERATE_SMALL", ["Conglobberate (Small)", 0]],
  ["CONGLOBBERATE_MEDIUM", ["Conglobberate (Medium)", 0]],
  ["CONGLOBBERATE_LARGE", ["Conglobberate (Large)", 0]],
  ["TOMA_CHUNK", ["Toma Chunk", 2302]],
  ["STROBILA", ["Strobila", 0]],
  ["GLOBWAD", ["Globwad", 0]],
  ["LONELY_KNIGHT", ["Lonely Knight", 0]],
  ["LONELY_KNIGHT_BRAIN", ["Lonely Knight Brain", 0]],
  ["LONELY_KNIGHT_SHELL", ["Lonely Knight Shell", 0]],
  ["CAVE_SPIDER", ["Cave Spider", 0]],
  ["RIPCORD", ["Ripcord", 0]],
  ["BEAD_FLY", ["Bead Fly", 0]],
  ["BEAD_FLY_CHAIN", ["Bead Fly Chain", 0]],
  ["RIPCORD_RING_GIB", ["Ripcord Ring Gib", 1]],
  ["BEAD_FLY_OUTLINE", ["Bead Fly Outline", 2]],
  ["NERVE_ENDING_NO_SHADOW", ["Nerve Ending (No Shadow)", 1980]],
  ["SPOOP", ["Spoop", 0]],
  ["SPOOP_TRAIL", ["Spoop Trail", 10]],
  ["SPOOP_TRAIL", ["Spoop Trail", 11]],
  ["CROCA", ["Croca", 0]],
  ["HAEMO", ["Haemo", 0]],
  ["HAEMO_GLOBIN", ["Haemo Globin", 0]],
  ["CHOPS", ["Chops", 0]],
  ["CHOPS_RIB_PROJECTILE", ["Chops Rib Projectile", 0]],
  ["KNOT", ["Knot", 0]],
  ["LURKER", ["Lurker", 0]],
  ["LURKER_CORE", ["Lurker Core", 0]],
  ["LURKER_TOOTH", ["Lurker Tooth", 0]],
  ["LURKER_STOMA", ["Lurker Stoma", 0]],
  ["LURKER_STRETCH", ["Lurker Stretch", 0]],
  ["LURKER_BRAIN", ["Lurker Brain", 0]],
  ["LURKER_COLLIDER", ["Lurker Collider", 0]],
  ["LURKER_STRETCH_COLLIDER", ["Lurker Stretch Collider", 0]],
  ["LURKER_PSEUDO_DEFAULT_SEGMENT", ["Lurker Pseudo Default Segment", 0]],
  ["LURKER_BRIDGE_PROJECTILE", ["Lurker Bridge Projectile", 0]],
  ["LURKER_CORD", ["Lurker Cord", 20]],
  ["SUPER_SHOTTIE", ["Super Shottie", 0]],
  ["SUPER_SHOTTIE_HOOK", ["Super Shottie Hook", 0]],
  ["PSIONIC_PORTAL", ["Psionic Portal", 30]],
  ["PORTAL_COLLECTIBLE", ["Portal Collectible", 31]],
  ["ROCK_BALL_MINES", ["Rock Ball (Mines)", 744]],
  ["ROCK_BALL_MINES_LAVA", ["Rock Ball (Mines Lava)", 752]],
  ["ROCK_BALL_ASHPIT", ["Rock Ball (Ashpit)", 760]],
  ["ROCK_BALL_ASHPIT_LAVA", ["Rock Ball (Ashpit Lava)", 768]],
  ["ROCK_BALL_GOLD", ["Rock Ball (Gold)", 776]],
  ["ROCK_BALL_TUMBLEWEED", ["Rock Ball (Tumbleweed)", 784]],
  ["ROCK_BALL_FOOTBALL", ["Rock Ball (Football)", 792]],
  ["MASSIVE_AMETHYST_CLUSTER", ["Massive Amethyst Cluster", 0]],
  [
    "FLOATING_MASSIVE_AMETHYST_CLUSTER",
    ["Floating Massive Amethyst Cluster", 0],
  ],
  ["MAGLEECH", ["Magleech", 0]],
  ["MYIASIS", ["Myiasis", 0]],
  ["MYIASIS_PROJECTILE", ["Myiasis Projectile", 0]],
  ["VISCERSPIRIT", ["Viscerspirit", 0]],
  ["MORVID", ["Morvid", 0]],
  ["MORVID_PERCHED", ["Morvid (Perched)", 1]],
  ["HOOLIGAN", ["Hooligan", 0]],
  ["GLASS_EYE", ["Glass Eye", 0]],
  ["TAGBAG", ["Tagbag", 0]],
  ["SLEEPER", ["Sleeper", 0]],
  ["NIGHT_TERRORS", ["Night Terrors", 0]],
  ["TRASHBAGGER", ["Trashbagger", 0]],
  ["STOMY", ["Stomy", 2]],
  ["PIPENECK", ["Pipeneck", 0]],
  ["CAPPIN", ["Cappin", 0]],
  ["SHOTTIE", ["Shottie", 0]],
  ["SHI", ["Shi", 0]],
  ["ONLOOKER", ["Onlooker", 0]],
  ["PUNTED", ["Punted", 0]],
  ["CUFFS", ["Cuffs", 0]],
  ["EMPATH", ["Empath", 0]],
  ["MANIC_FLY", ["Manic Fly", 0]],
  ["WARBLE", ["Warble", 0]],
  ["WARBLE_TAIL", ["Warble Tail", 10]],
  ["RIFT_WALKER", ["Rift Walker", 0]],
  ["RIFT_WALKER_GFX", ["Rift Walker (gfx)", 10]],
  ["FISHFREAK", ["Fishfreak", 0]],
  ["FISHFREAK_PILE", ["Fishfreak (pile)", 1]],
  ["KING", ["King", 0]],
  ["PAWN", ["Pawn", 0]],
  ["KING_CORD", ["King Cord", 23]],
  ["KING_CORD_HITBOX", ["King Cord Hitbox", 10]],
  ["FOETUS", ["Foetus", 0]],
  ["FOETU", ["Foetu", 1]],
  ["FOETUS_CORD", ["Foetus Cord", 10]],
  ["ANEMONE", ["Anemone", 0]],
  ["ORALOPEDE", ["Oralopede", 0]],
  ["ORALID", ["Oralid", 0]],
  ["THRALL", ["Thrall", 0]],
  ["THRALL_CORD", ["Thrall Cord", 1]],
  ["BLASTED", ["Blasted", 0]],
  ["BLASTED_MINE", ["Blasted Mine", 0]],
  ["ZEALOT", ["Zealot", 0]],
  ["ZEALOT_CROSSHAIR", ["Zealot Crosshair", 0]],
  ["ZEALOT_BEAM", ["Zealot Beam", 1]],
  ["SKULLTIST", ["Skulltist", 0]],
  ["RING_LEADER", ["Ring Leader", 0]],
  ["CHERUB", ["Cherub", 0]],
  ["DUNGEON_MASTER", ["Dungeon Master", 0]],
  ["RED_KEY_FIEND", ["Red Key Fiend", 0]],
  ["BLUE_KEY_FIEND", ["Blue Key Fiend", 1]],
  ["GREEN_KEY_FIEND", ["Green Key Fiend", 2]],
  ["DUNGEON_LOCKER", ["Dungeon Locker", 0]],
  ["DUNGEON_LOCK", ["Dungeon Lock", 2]],
  ["COCONUT", ["Coconut", 0]],
  ["ASHTRAY", ["Ashtray", 0]],
  ["CLOGMO", ["Clogmo", 0]],
  ["CLOGMO_PIPE", ["Clogmo Pipe", 0]],
  ["CLOGMO_TUNNEL_HORIZONTAL", ["Clogmo Tunnel (Horizontal)", 0]],
  ["CLOGMO_TUNNEL_VERTICAL", ["Clogmo Tunnel (Vertical)", 0]],
  ["MAYFLY", ["Mayfly", 0]],
  ["FISHY", ["Fishy", 0]],
  ["NECROTIC", ["Necrotic", 1]],
  ["FISH", ["Fish", 2]],
  ["CATFISH", ["Catfish", 0]],
  ["LARGE_WATER_RIPPLE", ["Large Water Ripple", 3]],
  ["SQUID", ["Squid", 0]],
  ["BUB", ["Bub", 0]],
  ["MOLLY", ["Molly", 0]],
  ["MOLLY_STAGE_2", ["Molly (Stage 2)", 1]],
  ["MOLLY_STAGE_3", ["Molly (Stage 3)", 2]],
  ["MOLLY_STAGE_4", ["Molly (Stage 4)", 3]],
  ["SHIRK", ["Shirk", 0]],
  ["SHIRK_SPOT", ["Shirk Spot", 0]],
  ["ROASTY", ["Roasty", 0]],
  ["LURCH", ["Lurch", 0]],
  ["LURCH_GUTS", ["Lurch Guts", 450]],
  ["LURCH_GUT_TIP", ["Lurch Gut Tip", 0]],
  ["JAMMED", ["Jammed", 0]],
  ["RED_JAMMED", ["Red Jammed", 1]],
  ["HOSTLET", ["Hostlet", 250]],
  ["RED_HOSTLET", ["Red Hostlet", 251]],
  ["GLORF", ["Glorf", 0]],
  ["ROTDRINK", ["Rotdrink", 0]],
  ["ROTSKULL", ["Rotskull", 1]],
  ["SLIM_SHADY_NOVA", ["Slim Shady Nova", 4]],
  ["GUT_KNIGHT", ["Gut Knight", 0]],
  ["KUKODEMON", ["Kukodemon", 0]],
  ["MAZE_RUNNER", ["Maze Runner", 0]],
  ["MAZE_RUNNER_RED", ["Maze Runner (Red)", 1]],
  ["BUNKTER", ["Bunkter", 0]],
  ["BUNKTER_TRASH", ["Bunkter Trash", 5]],
  ["WEEPER", ["Weeper", 0]],
  ["TOMMY", ["Tommy", 0]],
  ["BENNY", ["Benny", 0]],
  ["SHOCK_COLLAR", ["Shock Collar", 0]],
  ["CATHY", ["Cathy", 0]],
  ["SHOT_FLY", ["Shot Fly", 0]],
  ["SHOTER", ["Shoter", 0]],
  ["SOUNDMAKER_FLY", ["Soundmaker Fly", 250]],
  ["ARCANE_CREEP", ["Arcane Creep", 0]],
  ["NIHILIST", ["Nihilist", 0]],
  ["NIHILIST_AURA", ["Nihilist Aura", 6]],
  ["MOLAR_SYSTEM", ["Molar System", 0]],
  ["MOLAR_ORBITAL", ["Molar Orbital", 0]],
  ["PUFFER", ["Puffer", 0]],
  ["DOLPHIN", ["Dolphin", 0]],
  ["FLESH_SISTREN", ["Flesh Sistren", 0]],
  ["MADHAT", ["Madhat", 0]],
  ["GRIMOIRE", ["Grimoire", 0]],
  ["GRIMOIRE_FLAME", ["Grimoire Flame", 7]],
  ["PAPER_GIB", ["Paper Gib", 8]],
  ["SHADOW_SHIELD", ["Shadow Shield", 9]],
  ["LEMON_MISHAP_ENEMY", ["Lemon Mishap (Enemy)", 450]],
  ["ZTEWIE", ["Ztewie", 0]],
  ["ZTEWIE_STINGER", ["Ztewie Stinger", 0]],
  ["ZTEWIE_CORD", ["Ztewie Cord", 451]],
  ["DUMMY_EFFECT", ["Dummy Effect", 10]],
  ["DROOLIE", ["Droolie", 0]],
  ["MARLIN", ["Marlin", 0]],
  ["MIGHTFLY", ["Mightfly", 0]],
  ["GOLDEN_MIGHTFLY", ["Golden Mightfly", 0]],
  ["TRICKO", ["Tricko", 0]],
  ["DOLLOP", ["Dollop", 0]],
  ["FLYING_DRIP", ["Flying Drip", 11]],
  ["APEGA", ["Apega", 0]],
  ["MOLARGAN", ["Molargan", 0]],
  ["FLYING_ORALID", ["Flying Oralid", 12]],
  ["STERALIS", ["Steralis", 0]],
  ["DOGROCK", ["Dogrock", 0]],
  ["CHERUBSKULL", ["Cherubskull", 0]],
  ["CHERUBSKULL_HAND", ["Cherubskull Hand", 0]],
  ["CHERUBSKULL_CHAIN", ["Cherubskull Chain", 13]],
  ["FLYING_SPICY_DIP", ["Flying Spicy Dip", 14]],
  ["REVERSE_BLOOD_POOF", ["Reverse Blood Poof", 15]],
  ["MOTHMAN", ["Mothman", 0]],
  ["ASTROSKULL", ["Astroskull", 0]],
  ["LIL_JUNKIE", ["Lil' Junkie", 0]],
  ["QUITTER", ["Quitter", 0]],
  ["RUFUS", ["Rufus", 0]],
  ["TOOTHACHE", ["Toothache", 0]],
  ["RETCH", ["Retch", 0]],
  ["OBSERVER", ["Observer", 0]],
  ["CUSTOM_TRACER", ["Custom Tracer", 16]],
  ["ALEYA_FIRE_PLACE", ["Aleya Fire Place", 4]],
  ["ALEYA", ["Aleya", 0]],
  ["THUMPER", ["Thumper", 0]],
  ["NUBERT", ["Nubert", 1]],
  ["THUMPER_PEG", ["Thumper Peg", 17]],
  ["CHUNKY", ["Chunky", 0]],
  ["GRILLED_CHUNKY", ["Grilled Chunky", 1]],
  ["BUTT_FLY", ["Butt Fly", 0]],
  ["DRUMSTICK", ["Drumstick", 0]],
  ["SPONGE", ["Sponge", 0]],
  ["HERMIT", ["Hermit", 0]],
  ["BRIAR", ["Briar", 0]],
  ["BRIAR_THISTLE_PROJECTILE", ["Briar Thistle Projectile", 0]],
  ["BRIAR_STINGER_PROJECTILE", ["Briar Stinger Projectile", 0]],
  ["BRIAR_STINGER_POOF", ["Briar Stinger Poof", 18]],
  ["GRAZER", ["Grazer", 0]],
  ["PLEXUS", ["Plexus", 0]],
  ["NERVIE", ["Nervie", 0]],
  ["NERVIE_POINT", ["Nervie Point", 0]],
  ["INFECTED_MUSHROOM", ["Infected Mushroom", 0]],
  ["INFECTED_GROWTH", ["Infected Growth", 19]],
  ["INFECTED_RING", ["Infected Ring", 20]],
  ["CAIRN", ["Cairn", 0]],
  ["COUPILE", ["Coupile", 0]],
  ["COALBY", ["Coalby", 0]],
  ["COALSCOOP_COAL", ["Coalscoop Coal", 0]],
  ["BLARE", ["Blare", 0]],
  ["POTLUCK", ["Potluck", 0]],
  ["BETTER_COIN_PROJECTILE", ["Better Coin Projectile", 0]],
  ["CASUALTY", ["Casualty", 0]],
  ["SHRUNKEN_HEAD", ["Shrunken Head", 0]],
  ["DIM", ["Dim", 0]],
  ["DIMS_SOUL", ["Dim's Soul", 0]],
  ["TRAILBLAZER", ["Trailblazer", 0]],
  ["TRAILBLAZER_FLAME_SEGMENT", ["Trailblazer Flame Segment", 1]],
  ["GAMPER", ["Gamper", 0]],
  ["GAMPER_GUTS", ["Gamper Guts", 0]],
  ["GAMPER_CHAIN", ["Gamper Chain", 23]],
  ["WAILER", ["Wailer", 0]],
  ["SPELEO", ["Speleo", 0]],
  ["CRAIG", ["Craig", 0]],
  ["ROY_GERALD_DERICOTT_II", ["Roy Gerald Dericott II", 0]],
  ["CHILI", ["Chili", 0]],
  ["LITLING", ["Litling", 0]],
  ["GOLDEN_FLY_BOMB", ["Golden Fly Bomb", 0]],
  ["NAILHEAD", ["Nailhead", 0]],
  ["NAILHEAD_NAIL", ["Nailhead Nail", 24]],
  ["VACUOLE", ["Vacuole", 0]],
  ["BAMBOO_CUTTER", ["Bamboo Cutter", 0]],
  ["FRAYED_NERVE", ["Frayed Nerve", 0]],
  ["CONTESTANT", ["Contestant", 0]],
  ["SCREW_PROJECTILE", ["Screw Projectile", 0]],
  ["SKITTER_SKULL", ["Skitter Skull", 0]],
  ["WASTY", ["Wasty", 0]],
  ["TEMPTRESS", ["Temptress", 0]],
  ["TEMPTRESS_HOLE", ["Temptress Hole", 25]],
  ["DUMPTRUCK", ["Dumptruck", 0]],
  ["PILLAR_JOHN", ["Pillar John", 0]],
  ["LITTLE_JOHN", ["Little John", 0]],
  ["PILLAR_JOHN_QUAKE", ["Pillar John Quake", 0]],
  ["LITTLE_JOHN_POINT", ["Little John Point", 0]],
  ["ZEPHYR", ["Zephyr", 0]],
  ["ZEPHYR_LIGHTNING", ["Zephyr Lightning", 26]],
  ["FLAGPOLE", ["Flagpole", 0]],
  ["FLAGPOLE_BODY", ["Flagpole Body", 0]],
  ["TRIHORF", ["Trihorf", 0]],
  ["THUMBS_UP_FLY", ["Thumbs Up Fly", 0]],
  ["FLY_WHO_HAS_GREEN_AND_LONG_BODY", ["Fly who has green and long body", 0]],
  ["GOLDEN_SPIDER", ["Golden Spider", 0]],
  ["SLOTHS_HEAD", ["Sloth's Head", 0]],
  ["TAINTED_SPIT", ["Tainted Spit", 333]],
  ["IDPD_GRUNT", ["IDPD Grunt", 0]],
  ["IDPD_INSPECTOR", ["IDPD Inspector", 0]],
  ["IDPD_SHIELDER", ["IDPD Shielder", 0]],
  ["IDPD_GRENADE", ["IDPD Grenade", 0]],
  ["IDPD_PROJECTILE", ["IDPD Projectile", 0]],
  ["IDPD_SLUG_PROJECTILE", ["IDPD Slug Projectile", 0]],
  ["IDPD_PORTAL", ["IDPD Portal", 0]],
  ["IDPD_EXPLOSION", ["IDPD Explosion", 1]],
  ["IDPD_PARTICLE", ["IDPD Particle", 2]],
  ["IDPD_SLUG_POOF", ["IDPD Slug Poof", 3]],
  ["IDPD_GUN", ["IDPD Gun", 4]],
  ["IDPD_CORPSE", ["IDPD Corpse", 5]],
  ["BEACON", ["Beacon", 0]],
  ["BUCK", ["Buck", 0]],
  ["LEZ", ["Lez", 100]],
  ["BATTIE", ["Battie", 0]],
  ["BUSTER", ["Buster", 0]],
  ["COMMISSION", ["Commission", 0]],
  ["GRIDDLE_HORN", ["Griddle Horn", 0]],
  ["MONSOON", ["Monsoon", 0]],
  ["THE_SUN", ["The Sun", 0]],
  ["VENUS", ["Venus", 0]],
  ["EARTH", ["Earth", 0]],
  ["NEPTUNE", ["Neptune", 0]],
  ["MOON", ["Moon", 0]],
  ["SUN_SPIKE", ["Sun Spike", 0]],
  ["CHASER", ["Chaser", 0]],
  ["CHASER_BRAIN", ["Chaser Brain", 1]],
  ["BASHFUL", ["Bashful", 0]],
  ["BASHFUL_CORPSE", ["Bashful Corpse", 1]],
  ["SPEEDY", ["Speedy", 0]],
  ["POKEY", ["Pokey", 0]],
  ["POKEY_CORPSE", ["Pokey Corpse", 1]],
  ["BASCO", ["Basco", 0]],
  ["BASCOS_FOOD", ["Basco's Food", 0]],
  ["KINGPIN", ["Kingpin", 0]],
  ["PEEPING", ["Peeping", 0]],
  ["PEEPING_PHASE_2", ["Peeping (Phase 2)", 0]],
  ["PEEPSTALK", ["Peepstalk", 0]],
  ["PEEPEE", ["Peepee", 0]],
  ["LUNCHEON", ["Luncheon", 0]],
  ["TAPEWORM", ["Tapeworm", 0]],
  ["GENERIC_EGG", ["Generic Egg", 0]],
  ["PETUNIA_EGG", ["Petunia Egg", 1]],
  ["GREG_EGG", ["Greg Egg", 2]],
  ["MINKUS_EGG", ["Minkus Egg", 3]],
  ["BORIS_EGG", ["Boris Egg", 4]],
  ["WORM_BALL", ["Worm Ball", 0]],
  ["POLLUTION", ["Pollution", 0]],
  ["POLLUTION_HORSEPOWERED", ["Pollution (Horsepowered)", 0]],
  ["MELTDOWN", ["Meltdown", 0]],
  ["MELTDOWN_RAPTURED", ["Meltdown (Raptured)", 0]],
  ["FAKE_HORSE", ["Fake Horse", 0]],
  ["AQUAGOB", ["Aquagob", 0]],
  ["AQUABAB", ["Aquabab", 0]],
  ["DUSK", ["Dusk", 0]],
  ["DUSKS_HAND", ["Dusk's Hand", 0]],
  ["TSAR", ["Tsar", 0]],
  ["TSARBALL_1", ["Tsarball 1", 0]],
  ["TSARBALL_2", ["Tsarball 2", 1]],
  ["TSARBALL_3", ["Tsarball 3", 2]],
  ["TSARBALL_4", ["Tsarball 4", 3]],
  ["TSARBALL_5", ["Tsarball 5", 4]],
  ["TSARBALL_6", ["Tsarball 6", 5]],
  ["BIG_PIPE", ["Big Pipe", 0]],
  ["BIG_GRATE", ["Big Grate", 0]],
  ["CACAMANCER", ["Cacamancer", 0]],
  ["CACAMANCERS_BALL", ["Cacamancer's Ball", 0]],
  ["GUTSO", ["Gutso", 0]],
  ["SLINGER", ["Slinger", 0]],
  ["TOOTHACHE_TOOTH", ["Toothache Tooth", 0]],
  ["SLINGER_HEAD", ["Slinger Head", 0]],
  ["THROWN_ORALID", ["Thrown Oralid", 0]],
  ["DETACHED_SHADOW", ["Detached Shadow", 12]],
  ["STRINGSHOT", ["Stringshot", 13]],
  ["MR_DEAD", ["Mr. Dead", 0]],
  ["MR_DEADS_EYE", ["Mr. Dead's Eye", 0]],
  ["BONEY_BALL", ["Boney Ball", 14]],
  ["DEAD_GEYSER", ["Dead Geyser", 15]],
  ["WARP_ZONE", ["Warp Zone", 0]],
  ["CORRUPTED_MONSTRO", ["Corrupted Monstro", 0]],
  ["CORRUPTED_LARRY", ["Corrupted Larry", 0]],
  ["CORRUPTED_GEMINI", ["Corrupted Gemini", 0]],
  ["CORRUPTED_SUTURE", ["Corrupted Suture", 0]],
  ["PALE_GUSHER", ["Pale Gusher", 0]],
  ["GHOSTBUSTER", ["Ghostbuster", 0]],
  ["EMMISSION", ["Emmission", 0]],
  ["CONGRESSING_EMMISSION", ["Congressing Emmission", 0]],
  ["EMMISSION_PROJECTILE", ["Emmission Projectile", 0]],
  ["GHOSTBUSTER_DEATH_HITBOX", ["Ghostbuster Death Hitbox", 0]],
  ["WHISPERS_CONTROLLER", ["Whispers Controller", 0]],
  ["THE_WHISPERS", ["The Whispers", 0]],
  ["WHISPER_MARKER", ["Whisper Marker", 0]],
  ["VENUS", ["Venus", 0]],
  ["VENUS_DYING", ["Venus (Dying)", 1]],
  ["CACOPHOBIA_RENDERER", ["Cacophobia Renderer", 0]],
  ["MADOMME", ["Madomme", 0]],
  ["MADOMMES_SKULL", ["Madomme's Skull", 0]],
  ["BALLGAG_PROJECTILE", ["Ballgag Projectile", 0]],
  ["MADOMME_DASH_BALL", ["Madomme Dash Ball", 0]],
  ["MADOMME_BRIMSTONE_BALL", ["Madomme Brimstone Ball", 0]],
  ["GIMP", ["G-Imp", 0]],
  ["CASTLE", ["Castle", 0]],
  ["GLORIA", ["Gloria", 0]],
  ["HORSE_MADOMME", ["Horse (Madomme)", 0]],
  ["CHAMP", ["Champ", 0]],
  ["MADOMME_SPAWNER", ["Madomme Spawner", 0]],
  ["FIZSH", ["Fizsh", 0]],
  ["JUNKSTRAP", ["Junkstrap", 0]],
  ["DOPES_HEAD_PROJECTILE", ["Dope's Head Projectile", 0]],
  ["TEMPORARY_SPIKES", ["Temporary Spikes", 21]],
  ["PIGSKIN_TARGET", ["Pigskin Target", 22]],
  ["TRASHBAG_PROJECTILE", ["Trashbag Projectile", 0]],
  ["FROG_PROJECTILE", ["Frog Projectile", 0]],
  ["FROG_BLOOD_PROJECTILE", ["Frog Blood Projectile", 0]],
  ["PIGSKIN_PROJECTILE", ["Pigskin Projectile", 0]],
  ["BLUE_HORF", ["Blue Horf", 0]],
  ["BLUE_HORF_2", ["Blue Horf 2", 1]],
  ["DUKE_OF_DEMONS", ["Duke of Demons", 0]],
  ["DUKES_DEMON", ["Duke's Demon", 0]],
]);
