/** EID Icon Markup. */

// TODO: Finish
export enum EIDMarkup {
  ERROR = "{{ERROR}}",
  ARROW_UP = "{{ArrowUp}}",
  ARROW_DOWN = "{{ArrowDown}}",
  WARNING = "{{Warning}}",
  BLANK = "{{Blank}}",
  THROWABLE = "{{Throwable}}",
  CHARGEABLE = "{{Chargeable}}",
  QUALITY_0 = "{{Quality0}}",
  QUALITY_1 = "{{Quality1}}",
  QUALITY_2 = "{{Quality2}}",
  QUALITY_3 = "{{Quality3}}",
  QUALITY_4 = "{{Quality4}}",
  HEART = "{{Heart}}",
  HALF_HEART = "{{HalfHeart}}",
  ETERNAL_HEART = "{{EternalHeart}}",
  EMPTY_HEART = "{{EmptyHeart}}",
  BLENDED_HEART = "{{BlendedHeart}}",
  BONE_HEART = "{{BoneHeart}}",
  HALF_BONE_HEART = "{{HalfBoneHeart}}",
  EMPTY_BONE_HEART = "{{EmptyBoneHeart}}",
  SOUL_HEART = "{{SoulHeart}}",
  HALF_SOUL_HEART = "{{HalfSoulHeart}}",
  BLACK_HEART = "{{BlackHeart}}",
  HALF_BLACK_HEART = "{{HalfBlackHeart}}",
  GOLDEN_HEART = "{{GoldenHeart}}",
  COIN_HEART = "{{CoinHeart}}",
  HALF_COIN_HEART = "{{HalfCoinHeart}}",
  EMPTY_COIN_HEART = "{{EmptyCoinHeart}}",
  ROTTEN_HEART = "{{RottenHeart}}",
  BROKEN_HEART = "{{BrokenHeart}}",
  ROTTEN_BONE_HEART = "{{RottenBoneHeart}}",
  UNKNOWN_HEART = "{{UnknownHeart}}",
  HOLY_MANTLE_SMALL = "{{HolyMantleSmall}}",
  HOLY_MANTLE = "{{HolyMantle}}",
  KEY = "{{Key}}",
  GOLDEN_KEY = "{{GoldenKey}}",
  BOMB = "{{Bomb}}",
  GOLDEN_BOMB = "{{GoldenBomb}}",
  COIN = "{{Coin}}",
  RUNE = "{{Rune}}",
  CARD = "{{Card}}",
  RED_CARD = "{{RedCard}}",
  PILL = "{{Pill}}",
  BATTERY = "{{Battery}}",
  POOP_PICKUP = "{{PoopPickup}}",
  GRAB_BAG = "{{GrabBag}}",
  BLACK_SACK = "{{BlackSack}}",

  // Colors.
  COLOR_LIME = "{{ColorLime}}",
  COLOR_RESET = "{{ColorReset}}",
  COLOR_PURPLE = "{{ColorPurple}}",
}
