/**
 * Collection of all InvertedItemActionSetBuilders, use ACTION_SET_BUILDER_MAP with one of these
 * values to get the InvertedItemActionSetBuilder.
 */
export enum InvertedItemActionSetBuilderReference {
  INVERTED_ITEM_ACTION_SET_DEFAULT,
  INVERTED_ITEM_ACTION_SET_HAPPY_DEFAULT,
  INVERTED_ITEM_ACTION_SET_ILOVEYOU_DEFAULT,
  INVERTED_ITEM_ACTION_SET_MORRIS_DEFAULT,
  INVERTED_ITEM_ACTION_SET_HICURDISMOS_DEFAULT,
  INVERTED_ITEM_ACTION_SET_MYDOOM_DEFAULT,
  INVERTED_ITEM_ACTION_SET_REVETON_DEFAULT,
}
